import os
# from plant_menu import run_plant_menu

def plant_biomes(arboretum, plant, menu, plant_menu, error_message="Select the number of the biome"):
    """Displays the appropriate biomes for the plant"""
    os.system('cls' if os.name == 'nt' else 'clear')

    env_char = {
        "rivers": True if hasattr(plant, "likes_freshwater") else False,
        "coastlines": True if hasattr(plant, "likes_salt") else False,
        "forests": True if hasattr(plant, "likes_shade") else False,
        "grasslands": True if hasattr(plant, "likes_sun") else False,
        "mountains": True if hasattr(plant, "likes_high_elevation") else False,
        "swamps": True if hasattr(plant, "likes_stagnant_water") else False
    }

    biomes_dict = dict()
    compatible_environment_types = list()
    for k, v in env_char.items():
        if v == True:
            compatible_environment_types.append(k)

    for k, v in arboretum.__dict__.items():
        if k in compatible_environment_types and len(v) > 0:
            for i, value in enumerate(v):
                biomes_dict[f"{value.name} [{str(value.id)[:8]}]"] = value

    biomes_dict_list = list(enumerate(biomes_dict.items()))

    if len(biomes_dict) == 0:
        print("**** There are no available environments for this plant ****")
        print(f"**** {plant.species.capitalize()} can survive in the following environments: ****")
        print()
        for env in compatible_environment_types:
            print(f" - {env.capitalize()}")
        print()
        print("Press ENTER to return to the main menu and annex more environments...")
        input(">")
        menu()
    else:
        print(" +-++-++-++-++-++-++-++-++-++-+++-+")
        print(" |  Select Biome to Add Plant To  |")
        print(" +-++-++-++-++-++-++-++-++-++-+++-+")
        print()
        print(f"0. Main Menu")
        for i, v in biomes_dict_list:
            print(f"{i+1}. {v[0].capitalize()} ({len((v[1].inhabitants)['Plants'])} plants)")
        print(f"{len(biomes_dict.items())+1}. Back to Plants")
        if error_message != "":
            print()
            print(error_message)
        choice = input("> ")

        message = """
            lloooddxdddocc:ccldoclocccxOOOxlldxkO00kO0xodkxkxdl:odlcloddddoodooodllxkk0KOkkkxxkOOOOOOOOOOxoO0O0XKKKOkOOO0K000KXOdolllodxxdxdc:,,,:loxO000OOKKOk0XKOOkxddxolooc:cc:c::oddodddocokkOOkkxlcoxkdodlcclollc:;c:'',;:;;::::::;;;;;;:cccooc:ccc:;',:cccllooc:;:;:clolccclodo:,,,,,,,,,',,,;:okkkdooclxOkl:lxdll
dddoc:llodddooc;::clcllccoxkxxooodxk00Ododollddodxddl;,;ldollccccc:cxOkxxxxkxxxxkOOkkkxdxOxoxkdxO000K0OdlllloxxxkOOkdoodxoldxxl:;,,,:kKOdkOkOO0KK000KK00Okkxoodoolccodooxococldddoodkkdoooocclolc:clc:clooccl;',;;;;:c:;;;;;;;;;,;;,;clllolllc;;;;:c:coo::lccllcc::cllcc;'''........',,,;:cxkxxoccllcoddxdll
ollc;,,:cllool::c;;:;:c:codolololoodOOxoodolollllodo:,'',:cclooddoddooddkkxxxdolokkxxkkxkkxdx0000OO00OOkocllodkkOOdooloollclxxo:;,;ckXXOkOxxKXXKK00KKKK0OOOkxkOxdxdoddodxdxklll:lldkdddodlooc:::;,;;,';coolc:;''',,;;:;,;;:ccc::;:::::::cc::cccccclcccc:;;cldooolcllc:,.........'''',,,;:cxkxxddx:,cooldxddd
;;;,'',;:::::::ccclc::::clc:ccloclodxdolloc:ccc:;,,'..',;oxxkOkxdxOkdccloddxk0OddkkkOOkkO000kkOOO0OxoooooodddxkkO0Oxollooollolc;',cxKKkxkO0O0K0K00KKK00OkkkxxkOOO00OddO0Oxolcclclooxxccdxlclc::;;,,'';:;;:c:c:'.',,'''',,,;loooolc::cc:,;:;;::cc::clclddloxxdodkxoooc:,','....',,,,;;:;cdxk00d:cccldOOkOkoc:
'''.',,,;;;:;,:cc:::cc:;,;;;;;cc:cllcclccl,.',;,'''',;:ccoddO000K000kxdodxkkkkddxkxddodk00KXKOOkddxdoccolodxxkkxdxkxdolodlclllc,'':dkO0KKKK0OOOOkkkkkkkkkO0OOOOO0OO0kdOOdolcdkkxdocldc;:ll:clll;,''.',;::lddl;..'''.''''',,;:ccccccc::;:c:;:ccccc::c:col:coc::cclddccdoll:'',;;,'',:::cdOkoodl:lloxxkxocc::l
;,,,,;::;;,,,;cc:;;:;:lc;',:lclc;;clcclll:....',;:c:::cllclxk0KK0OkkOO0OOOkxdoooodxkkkkkOOO0K0kddloxxxxdxO0kodxxdkOOOOOOddxddko,'',lkOO0OO00kdxkkddddk0Okk0XX0kk0KKKkxkoc:ldxkxxd:,:ll;';c:;:l;,,,'',,:lolllc'..''''..',;;,,::;:::;;;,,;llccl:;;;;;:::;;;llcclodk0xccllc;'.,;cc,,,,:::okkdlcllldololcclodxxd
ccooc;;;;;;'';cc;;;:;,;::;';xo:lollldxolc,..,;:cllocccloocokkkkOOkkxdxO00OxoooolldkO00xodddkkOOkkxooxkkkO0OdldxxO0Ododxxddddkkx:''':OXkxkxodxxooxOKOxkOOO00OOkxk0KK0dlolooldxxOxoc;;,;,',::;;;;,.';;',;;:ll:;'..'',;;,;::;:;;;::clc:,,;clccc:;,,;;;;:cll:c:;;:loddlll:,....,,:,',,;:coddlcclxxdc;;:odddxdxOk
loxxdl:;;:;.':cc:;;;;;,;;,';llcclccc::;,,'..,codllooodxkoldkxdddxodxdddddddl::lllodooooldxdlloooddxdddxkxxxdooooxOkxdolloxOkxxxl,'',oKKOOxdxOO0Ok0XXXkdxkOkxxxkOK0Okdlollodkdxxodoc;,;,',c:,,;;,',::,,::;::,,'..';c:;;;:;;;;::lol:cccccc::c:::::;;cllxxlccccc:;coolooc'..';,,,',,;::lkkxkdcoxoooddxOkooxxk00
ddxddolcc:,',;;::;;:clc,'.''',,',,'''.......':dkxdxkxxdllxkooloollxxxdoc::llcclccccldoccddol:ccllodddodolllodxxdxOOO00Oxddxxxkkl,'.,:OXOkkxdkkkOKXK0OkkO0KOkkkddxkxdoloxxkxdxkkxoc;:c;,,,::;;,,;;,;cc::,';:'''....,;,;;;:::clccl;,;:ccloolllc:cc:::oddl::ccloc:cldxxxd;.,,,'''',,;;cxOkkxlcclx0Kxdxkdlxxddkk
coxxdoc:;:,''',,',,:l:'...'''',';:,';;;::;cllllddddxxdoodkkxxdxxllooddollcllloc::cc:::::looooollddoodooddoddddddxxkkkk00O0Oxdol:,''':O0xdkOddkO00OkkO00KKKOO00xddxddooodxkkxxkkxdlc:::::;:oc;:;::;:ddc;;;,,,,;,...';;;,;;::cccc:;;:cclddolllccclcccool:;::;;:;;;coool;,,,'',,'',;,:ooc:clodkOO0Odddooddoodxx
c:::clc;,;,,'',,,,,;:,.';cc;;:::c:;;;;:cccclccloooxxollooodoodxdlcllccloooddoodddolc:::cccccclooxdooddcoxkxxxdoodxkkkkO0kdoxoc:;,'''cO0dxOkook0KkxkOOOkO00OO0Oxdoodoldxlodoloddl:clc:ccllcllc::cc:clc;;,,;;::c:'...,:c:;:clc:clcllclldxoc:ccc:;:lcloc::clllc;,;:loc;'.'''',''',,,;cdooxook0Oxooxxdddxo:coxdo
coo::;;;:;;;,',;;;;,,',odc:;;;;::col:;;,;:cccc:looxdc:doc::cloocllllllodxxOOxxxxkkkxocccc:cl::cooldxdo::ldxxdoxxxddk00Oxdooddlcc;;::lOXOdoodkkOOkxxxdxkkxkkkk0K00Okxkxc:lc;;;;:;,,',,,:cc:cddolc:;:ll:;,,,:ll:,'....':l::ccc;;coolcclolc:cllc::lc:ccccloc:ccclodkkl,''.'''','',,;:ldxxdllolodxddxxxdl::loodx
oxoclc;:lc:cc'.,::;,';dxc,::::;;;:oocc:;:cc:ldoddoc:lodocllodoloxOkdoldkxxkkxdddkkkOOdlccccc:;:cccllll::cldoc:okOkkOkxoodxooolll:,,;cx00xoxxxkkkxkkxdxxddddxkOOkkxkOdc;:cc::cc;,,,',;;;ccccc:loollccl;,,,;coc''cl'...,cl:::;;:ldoc:::;:::lc:cc:::ccclllllclooooddl;''..',,,;;;:::cddl;,:cldddkdlxxxdlododdox
Oxc:cllloocod:'';;,;cdxl;';;;clccoolll;,:looodxoc;;cdoc:coxdodkkkkxxocokdoddodkxxdoxkxdlcoodolccllc:;,;clcc:;:cddldkoloodxdlolcc:,'',cd0KkkkdkOOO00OxkkOOkO00Oxxkkxdc;,,;,;cool:;;;;;:l:;cc:llccllcldl,','',;cccc;...':l:;:;,;::ccc::::clolclooolldxdl:cdkxkxdooc,...'..'''..';;lkkoollodxkxdooddoccddlcooll
Odllodkkddooddc;;,;lxxdl;:cc:coxkxxxdl;:oxxxlccc::loolokxlloxkolocllc;:ccc:::oddkkkxxdccoxddkkocodl:;,:cc::;;::c:cllllclccclolccc:,'';okkdxdclk00KK0OOOO0KKOkkkkOolol:::;,;:clc:cccc;:llccc:;;;;:odoc,.',''',;;:ll,..'';:;:looc:::codl:clooccodkkoloc::oO0OO0Oxc;,..'...''....';k0ocoxkOxoooxdloldxxolllloxx
OOkkOkkOkoolcl:;coddodl;;cloddxk00kxdlcllcclcclooodddxkkOkxk00xoooxdc:clclc:coodxOkdddl:ccoxOOdloo:;,,,::;;;::clc:::::lc:cloolc:c:;,',:dxolllccodxkkO000kxxxkxoodlldddl::;;:;:::looc::lolcoo;,::cccll;',,';;;;,,;::,..'';lodkdooxkkOOdlollllllllooddollclddkkdc;;;'''''..''''';xOocdxxO0ocxOkolxkO00xooollox
dddddddooc;;:::loc,,ld:,:oxkxxkOOkdolcokOxdxxkkOOdxxddkkkOOkkOOkOkdooodocllcccclolccllcc::oxdoloddlc::::cc:cloodoooolcclloxxxdc;,'''',;dOxooodxolxO0KOxooxkkxloxdldxddlcc:;::::loodxoc:clc;;,'cdolcllcloo:;;;;,;;:::;'..,:ldxooodxxk00OOkddk0Okxdk0OOxxdoolddl:,,,'''''''....,odloxkklokO0KKdlkK000kOxlcllco
;;;,,;;,;;,;ldxkxl;,;:;:ldolllooxkxkdlldO00000OOOxkOkOO0O00OddxOOOOkOOkxkkkdooooolclolllc:clllcoxddolddxkdlclkxodxxdoollloddoollll:'',;o00odkkkOdokOxlcoxOkxOOOOO00Oddoc;;;:ldlccccll:c:ll;:lc:ol,,lolccl:,,;;colloxxc'.',:dkOdloddk0kkO0KXXXNXkoxdkK0xoddlodl,.'''''''''...',okxdolcldkOKXXkoOOdOkoxklcllcc
ooollolodxxkkxxxdl:;;:lolc::;;cx00OOxkkO0OO0Oxx0kxxxxO0K0kdoollooodoodxxddddollolccoxkxxocclooldOxodxO0kkkxccdxxdxxdddoool:;:ccldxl,'',:k0kxkOOkxdcodxkkkOOO0KXKKOxdcccclcccloc;;,,,,,;,';;;:::c;',c::llc,,,,;:::coxxdl;',;cxOkOkxddOOO0XNNXXXXkxkkxdkdlddooo;..',,'''''..',:ldxxo::o0XOk00K0ddxxkkxdoc:cclo
0KK00Okkxxxxdlllc:::oxkkxolllldOK0OxxOOOOkdoolcoodddxkkkOkxxdc::::cc::clcll:::cl:;:coxkxl:;:ll:codcloolcdxxxlcd0OOkxxdoxxoc;;:ccldo:'.',lkkddkxk0OllO0OO000Okkkxxdoolcllolcc:lololcclol:;:;ccc:;,:cllcclc:;::::::cllcodo;',:cx000Oxk0xok0XXKkdxxxkdccokkxxko;''',,'''''.'';oOOooxd:;:oONXKkkX0dllddlclccoxkk
xxxddolccccccccc:::lkOkxxoodk0K000kkkOOkO0klccc:coodkkodOOOkdlcclccol:::;:c;,;;:c;;cc;;:c;,;::,;:c;;ccclodxkklcdkxddoclolcoollcclodl,.',;dOkkk0KXOccOKKXXXXOkxddxdddl:clllcclooooxdddolcc:;loolclodkkdoddollllccclkxlxxol;',;cd0XXXK00Okk0X0o:cdO0xddodxdlc;,'.';,''''''';lkkloollllclkKKkdx00xdddddddodxdxx
lllccccccc:coxxocccxOOkxxOOOkOKK0000KK0000kxoooc:::odoloddxxl:cll:;;:cc:;',;:cccc:;:ccc;,;;,;cc;;;,;coddoooxxl:lkxllolodlllllccloloo:''.,:dOxdxOKOccxKXXXXXXKkdddlldkoldxkxlloodolccll:,,',;;;,;loodocllclllddoxxxkkdkklll;',;oxkdxO0000xddxdc:lkKK0Oxc:oo;'''',,'..'''',:kkc:oddxxolxK0kO00XKkxddddddlccllo
c::::::::::lxkOkkxkOOkxoox00OO00KXXKOO00Kkdddodlcl::ccodxxkddllllc:;;:c::;,:::c:;;;;;;;::;:ll:clc:;;:cc::c:codl:oxxxxdodoooc::;clc:l:'''';xkxxO0OdclOXXXKOkkxddooooododxdxxodkxxoc:cllcc::c;,,';l::c;:cllloddk0K0kO00K0kddo;'':ldddxooloc:lddlcdOKkdkdcc:;,';;,,'...'''',okooxO0xclxxx0K000KNXOdlcloddoloddd
:;;;;:coooodkO0K0O0Odddoolx0OkkKKOkOOkkkkxoloododdccldxkkxddxl::::clcc::lccc:::,,:cccccldolxo;:c:,,;;:::clccdxl;cdxOkkdolllc:::;::;;,..'';kKxoOOdoldOKKXKOOkkkOkkxlloodddxoclc;clcclol;:oxko::;ldc;:cccokO0OkdoxkO00KX0Okxxc'',:dkkdodl:cccdxdk0K0koolol;,,';,''...'''',lOOkOOOkdodOXKK0KX0Okkxocooooddooxkd
lc:cldkxdodk0K0OO0OxxxooollodddkOxxkxkOOxddl;,;cdo:::cloolldo::cc:coolcccloolc;,,;:lolcldddooc,;lclooooddddodkxc;:oxOkdc::cc:cll:::'....';x0kddoc:ldxkOO0OxxOKKKK0Okkkxddc;::;:llc:::looxkko:cokkool;,;ldO0Okddxkkdddxkkxddl;'':x00OkkdlddoxkdOKkkKXKOd:;,'',,''..''','ckkodoloold0KKK0KKKOxdxdollodxdoodOOo
lclcccooodxO0KK000kxkkocclcododdodxxddxkdlc:;,,:lloolc;:cccol:ccc:codoc;;,,:c:;:;;;:c::lllodxxl;lxxkOkodk0KOO00dc;;cdkxoc:clcclddlcc:,..';lkkoc:;cdxolllooldOXXXKKKKK0kdl:;;;;;,;;,',ccclc:c:cdkxdl;,,:oloO000KKKkoooloodkOkl,,,cdkOO0KOxdkkxxkOOkOO0xc;,''''''''',,',:odooocccccldxxxk00OkkkOkxxdccoccodkdc
ollc:llcoxldOOO00kdddxxolooxkxollldxkkkxl:;;cc:ccclodolxxdlddllooool;;;;;,''''';::;;,',;::lddoo:;okOOkc:dOxdxkkkxdc;;lll:;;;;;:lodxxd:..',cxxc:::clolloollddk0KKK0kkkxo:;::;cc;,;;,,;:ccc::cooc::clc::ldloO0K00KKKKK0Okdlcldo;',:oxkkO0OxxkxxkOOOO0kl;;;'''''...''''':odooddolcll:cllodxkkkkkdllllcc:::llllc
xdxdollodddxOkkOkOOOkkkkxoooooccccdkkdllccc:cc::;:lcclodoolldoxOxooc;,;;;;:,''''';;,,',;:ccclc:c:;lxxxccdxoodkkdlc:;,;;:::;,,;;,;coodl'.',:x0koooldkOOOO0OOkOK0K0Okdolodlc::c:,;::,:llcccloo::;:clc::lkkloO0O0KKK00Okdooodxxxl'',lkkk0kdddxxxxxxxdl;;;,',,''....''''cddxkddddxdddc;::cloxxkkdl::c:cc:coddoll
kdddxkkkOOxoodddxkOkxkkxkxdl::ldocdOxcloollll:;;;c:,;cc;;::ccloodolc::cllccc;;:,,;:;,,::ccclododo;:dxxlcxxxkO0Oxl::loc;;:lc;;;;;;;::cc,..';oO0OxdldOKKKKKKXXXX0koclll:clc:clloxxl;:dxxl;;::::;,;:;,;cllc:okxk0000OkOOxddxkkkOx:..;dOkOxxxdlcoodo;,,;;,''''....'''',cddxkkkxddkkOOdlllccoxkxollcllcccodxOkoll
kdoxOkkOOxddlxxdxkOxooxkOkOOkdxkdcclcclool::;;;,,,,'''''.',,'',,,,;cc:;;;;,:ccc:;:ol,;:llldxooddxo;cxkdcodloxkOkdlldxdl;,;cllllolcolcc,..',cdxkdolcdkkx0XXKK000koc;:cccccokkocol;;oxddl::c:,,',;,,,,;;,,;lddxkkkkOOOO00OOkddxdl,.';oO0OOxdxdxoc;,;::,''''.....''',cdxxkOOkxdoodkOkxxoloollclllc::ldxdldkkxxo
kkOKOdodxxxxodkddkdooodkkOKOxdolc;;;::lolcclc;,,;;,',,'''',,,,,,'.,::,',;:loo:::cloc;:ccodoodxdoodl;lkxcoxlldkkdocllcc:cc::llccllcolc:,...,cldxxdllooodxkxdxxdolc;,;:llc:ldollllcoocloc:loccc,,,,,;;:;,,',;oooolodxkxodxxdoddol:'.,;okxxkkkOkl;:c::;,,'.....'''';ldddodkxoodddxxkxodkkOkxoddc;::::oxkxoloxxo
kdoodxddxkOOxx00xdolllodxkOdoolc::;,;;;;;;;;::,,,;,,,,';;:cc:::;,,,,;,',::clc::cc::codlcoddxkkkkxdd:,oxl:c::lol;,,,,;::lolc:;;,,;;:cl:,'..,:loodolodxO0Oxodxko:coooollc:cloooolccoccollolcokoc:;;;;,',::;:loc:::ldxocldkOkxkkxkkc.'':ddlloxo:;:c::;,''......',,:dxoodoodxkkkkkkOkxddkkdlldkkl:::::cloxxooxOx
dddloddddxxxxkOkkkkxlcloool:;;;;;;,',;;;;;,;;::,,;;;'''':lcc:lo:,;::clll:,;;,:cll:oxlldddookkkkddxdd:;oxlclccc:::,,',;:ldodddxxdoc;:c:;...';ldcclox0XK00Okxoc;cdOOOklc:collllxo::c:;:lxxllxxlccoxocc;;::;:::cccllllc:cclddlxOxdxx:..,;:lodl,';cc:;,'''..'..',,cxxlldkxddldxooooOkxkkdddooxxdlloddoolldxodO0O
xkkxoodolcc:colooolc::ccc:c::c::cl:;;:cllccccc;,;:::;;',:ccc::c;,,;llcl:;::,;;:occxxdxkxxkdooloddoool,;ol;::;:c:;;:;,:clodxkOxddolcloo:'..,;cdl,:lxxkO0Oxd:;cldOOk0KOkddxxxdodo:;clc;:dolll:;;;cl::c:,,,:lccoxoolc;;;;:looldkkkxxc,.';:dkl,';:::;,''......',,cxdcldk0Okkxoc:loddoldxlcc:clloddkOOxoldOkdk0OO
xOOO0kdocllc:cldxxdlccllcodooooodOkoldxollc;,;,';;;;:c:;;:c:,,;c;',,,,,;;,',;cldolocloddoolcloodxxxddl,,;,;cllll::c:;::ldxdddddoooddxxo;..',:dxc;cdxxxddl;;oOOO000OkOkdxxoccc::;,,;;',;;::,:c:;::;:;;;,,,,;;:llcooc::cllloddddolccc;..,coc;::;:;''...''..',,ckxlokOO0K0Okxdolol:;;;;:::coxdddodkxoldxkOkkkxO
kOxkxdxkkdocldxO0Okxxxxoccclldkkxdkdloddodxxl;',,,,:lol:;;::;;:lc;;;;;:::;,;codollcccldxdollodl:clodooc'';:col:::clolc:::lodxdc::clooool,...,cxxccodl;,:cck0OO0KKKOxkxloxkdddlc:;;::::cccllc:;lxxl:;;;,,;,,,;;;;cododdollool:;:ldddl;'.'cdoc:;,''..',;,'',;lOKOO0KK0KK00K0kx:;ll:,,,;;ldOKxooloddloxodO000O0
OkxddddkK0kx0KK0xk0OOOOkdlldxxOOxolc::lllxOxoc;,:::::::::clccloolccc:;,,,;;;ldlccl::oxddxdlclollcccodoo:.,::c::lolooddl:cooddc;,:c:loodxc'..';o0klll::cldk0kkO000KKKOxxdodllddolcoolllooldkkxolooc::oo:;:;;cc::;;cdkxxxdc:;;:ldxkkxkd;'':c:;,,''..',;;,',,lOK0KXX0OKK00K0xol;'':;',;cccdkxl:cllokkOKOkOkxxdx
OOxolldO00KKK0kdddxkOkxdxxddOOkkxololcoolddc:ll;,;;;,,cccoc,:lc:;,''''''',,,;;,,:l:;cldocll::oddodxkxooo:.';ldoolcc:coc:clodxdllcc:coxOOd;..'';d0kooddxxkOOxkOO0OkOkddkxoolc::loloo:;:ldkddxdool:cccll::cllolcllcc:codo;,,:ldxxdkkddo;.'::;,,'...',;;,'',ckkoox0klodoxxoccccc;;;cc;,coooocco::oxOOOOK0kdllod
dccloxkkOO00kdcclodooook0koxkxxxo::cccoxo:coddo:'';c;;looc::;:c:::;,''''''''',;cdxdclxkoldoloxxxkkkOkdool,.':lxkdol;;::,,;;:clollldooxkOko,...':x0dlooodkxdk00KK000kxdlldxolc:clc:c:;;:ldolccoxxxxl::coololclcc:::;;;;;;:lllllodddc:cl:;;;,'...'',;,''',lOxoxdodoll::ccllcccl:;;::;,;clcodollldkk0xloodxolox
lloxkxxxxdlllcccoolcoxO0Oxdooolc:,:l:;clc:;cdolo:,;;;codl,',;:;;:;;,,',;;:::::cdkxdllxkxxkddkkdxkkdoxOOxd:.,,:xkxdoc:c::,,,;:llcccclodxddxc....,ckOl:c::colxKK0Okk0KX0dcdO00Odlllcc:;:::coddllllloooddll:clooloo:;;:;:ccccddolldxdlclc;,,''...',;,'.'';dOxloxocclllodxo:;:c;;:;,;;;,;lodxlcldxOkdolclodxxdoo
xoodOkxk00kolodoccldxkkxxkkkxl:;,:::;;::;::;clloc;;,,,;;;,,::;;;;,,;;,:ccc:;:;:lc;;:lodddxookxddlldkOO0Okc';;':c:cccllloolclxdollol::codxOd,....,lkxc:;:cccokOOxdk0K0OkdOKOOkdodolc:;;:clooc:c::::oodxdoollllcccc;;;;cxdlllodxkko::;;,,'''....'''..',cxxl:clcc:::cllllcc;;:;,:cccllolcoxddxxxxxxdllldkkOklcc
dollxkk0XXKOkkxxxk00K0OxccxO0d:cc:::::c:;:ll:cl:,,cl:;:cc:;;;,;::;;:;;:coxoc;,c:;;;;::;::coddxkko:ldoloddc':dc,:ooooddoddxxkkdddoodoc:cldxxl,....,cxxc,;;;:ldkkxkO0OkkkxdxdxxkkOOddoolcldxxdolllc:::ldollolcloxdllclooxolc:lxkko;',,'''''''...'',;,;d0kloccol:::;:cdxxxdl;;:::loc:lolcoxxxxxxdddxkkxxkxkxlld
:loxkxkKXXKOxxO0OkkOOO00kkOkOOddkdl::col:cl:;:lc,';cc:cccc:;cc:ooc::;:lllxdc,,:,,,;::;;:;;cllll:;;:c:;:ldx:,lc;cxkkOkdl:;ccccxOxxoodxdlcldkkc....',:kx:;;;:cldkkOK0kxxdodxdxOxkOocoxoooclkOdooccc:::ccclodl:coxocloxO0KKOdc:::,,,'''''',,'...';ll;,lk0kool;,;cc,;:cxxdolccccll:cl:clc:lolcddddxxdkO0kolooodo
cooccclxxdooddxdolcoxxddddkOk000Odl::coollc:ll:c:',lllllclololc:::cclddoccc;,cc;;;;;:::;;,,;cc:;::;;;;:ldko'',;oxxkkd:,;coc':dxoooccllc:cldxo:'....'oOkl;;:;:cloddolcdOOdolccodolccoooddlodolccccc::;:llc:cllddoloxk0KKKKOdol;''''''.',,'..''lxo;'',:xkkxdlcclc:cc:cxOOkl:::cc:c::c:::ll::oxxk00kdxOOkxxO0Ox
ccllc:ccoloxddxdlloldxddxO00O00kxxddddOOdoclxOdc;',:;,,,;:lllc;;::lodxdddlc;,ccc:::cccl:;;;;clc:loloooloxxd;':dOkdc;,,;:cl::lodo:;;;;;ccodolll;...'.;kXx:::::c:cc:clllcc::clcodlloddxl:llccc:;,;;;;;;;;cc:odok0Odolcoxk0KKKx:,'''''.'',''.,cdxo:;,,'.,coodxdolc:::ldddxxo:c:;;;,,';lxl::;:lodkOOkkOO0X0xKKkd
dxkdlllldlcldkxxxxkOkk0000KXK0kooxkxxk0OdoodkOkl,;c;,;,,:::ldlcoxxoooxk0Oxo;,llcccccccc::;;;;::ldxdlodl:loc'';llcc:;;:ccclclloooolll:;::::cool:'...,,dKOl;:ccc:;;::c:::clc::oOOdcldlcc::;;;:::;::;:cccclooooclooc:clccdk0Oo;,,'''..',,,'';xOdllclol:,'',;cokOdoc;;:okOxlll:;::,.,cdoodlcccclclodkkO0O0kkK0xo
kxxdllodool:lkOxkkxOOkk0K0KKOxdccoodoooxxooxxxOx;,cool:::clddxocoxlclodddcc;;oc:coollc::c:;c:;lddxxoooloooc'..;ldxdoddolcoxxdddxkxdo:;cl;,:cllc,...';:codcclc::;::::;:lxOkooOOxdooooxkdolcooodxdc:codlldxdodocccclolclOOl;;;,'''...','',lkkl:lollllc;,'''':dko:cccddllloclc;;,..:lc:ldoccldxooloox00OxkkOxoo
OOOkkkkxdodc:lxkddxk000KK00kdxdlllcclcdxlcloodxo;';lxdlc:;coodkololoddoodxd:ldol:coooolc:;:::ldoxko;;:cclo:'.,lkxxdoddoccok0Okkddoc:,;::;;;;:cc:'..,;,,:dxdolc::cc::codxOOkxkxxxdkxlcccloodxdldxoloodxdolc:c:cooddllllc:;;;;,'.''..',';oOdcccc;,''''';:::clokd:;::coclxdlcloc,;;:c:::;;;codxkkdddxkkOKX0Odlo
kO0OxkOOkkxccccolcldkO0KKXKOkkdddooc::clcccccodo;:l:cxkxooooclkxlcloxxxddxd;:dxdc:clodoc::clodddoddlcxOoll'..,coooddooxkkxxxxdoc:;;:looc:;,:;::;'..';::cdkOoclollolcdOkO000KKkkxlldxodkddkxloodOOdddddoc:;:loloodxo:;,',;;,''.....',';dkxkxc;,'';::lldOkdkxoxkd::clc:clc:col,,;;col:;;cloxxooldOkkOO0K00Kkoo
odxxdkkk0OlclocccooodookO00OkxOOOOdllllolcllllol,:kx:cxxlc:llcddc;:cloddxo;,cdxxxollxkkxolxdcllc::lccdo;;,..',:cclclloxxxdol:cc:,,:odolc:,,c:;;,,,'.';clodxdldOkkOkkk0000K0xoooooxxxkxllldOxdolooodxolc:::;:llooccc:'.':;,,,,,...'',:xOxddl,'';o0xlxolooxdoollc:cclddllclodc;codkkxollookkkxoodkOO0OkxokOxdx
xkxO000kdlllccc;:lllkOxkkkkdoxkdkkodOkxxolxkOOkl';dxl;::;;:oo:clcldxllddl,':cldkxdodkkOOxccxxxdoc;;:c:,...';,,:cldo:;;cool::;;;',,:lcc:;:c::cccc:,''',;:cccoodOO0KXN0xO000OkkxdxkOdlxOkkOkdolcc:::lllc;,,;:dxllccc;'..,,'';::'..'',lOxloo:,,;ckKOoc::clxko::::c::llddddolccccodkkxxxxxdx0K0000kddxxxlcoxdooo
K00KKOxlodolll;,:cloxOkoooolloxkdodxkkdddlldxxxl';oxxc;clldko;cddddkOdcl,,collxkxdxdlcllolldxdooc::cl:;..'::::;;col;cocclc:;,,;:cllddxdldxoldkkkdc;,',,;::cloodxxk0Kxcodooxk0Ood00kkO00OOxdollcclccc:,,,:::oolc:;,.'',;'',;;'..',,l00l;;;,':xO00Okxdl:lodllolcoxxkdlloxd::ollxxccoxoooloxkk0OOOxdddocclooodd
00kxOOkdolcloc:;,,;codl;::coxdxxdkOOOkOOdoolclo:';cclc,;ccldl;:dOkxkOd;,:cccldxkOOOkdodlcldkxolc::codd:.'c:;;;cc:clclc::::,''';clddxxxxkOkdx000K0xc,,,;:cccclclodxkdc::::cllodxk00kkkkOOkxxkxdoc:;:c:;;;oxc:llc;''',:oc,',,''.',,l0Nk:,',;cdkOKXK0OkooxdllxxdoodxOOdoddc:dxo:clcclloddddxkkkO0Okkkkxlllloodd
doccllodllc:clc:::::cdl;;clodxkxO0OkkOdlllcc:::,':;;::;,,:ddc,;ldddl::;;::ccodxxddooddd::kkxdooddlloxd,'cdl:,;llloolc:;;;:;',;cloddxxxddOxdddxkkdl:,,:cc:cc:::cloxxl;::;:::cllloxxddxxO0kxkkkxolc:;;;:;cxxodko;'',;lkx:,;;'..'',:xNNkc:,':dxooOKXKOxlokkocxOOOdlcdOkkkooxdc:colcdxolldkxxOkxkOOkOkxxollclodx
ll:::;:c:cccc:,,;;,';c::cdxolxOOkxkoll::llloc;;,cxl:lll:,:c:;,,col,,:c:codddxOkxxkxoxkl:dO0Oxoloolcc:'.;ldlcoddlc::;,,,:l;;::lldxddxkkdlddolcllcc::,,;;;;:cc::ccldxdol:;:,';looddxkkddddoodoodlccccllloxxolc:;,'';okxc,,,'..''',:d0Xkoc';oddlldxxddoclolccdkOOxolodol:ldlll::cloodloollloxkkO00kxdoocodllox0
lcc:;cdo:coxxxl;;,;;:lddoolccloooxdl::ccllcccc:,o0o:;;cl:'':c:;ldc'lo::cdkkxxkxdddox0kokKkddxdolool:..':ol:cdddxxo:,,::cloxxolloxkOOO0Oocol;,,,';:;,,,,,:cccc::cldkOkxdc;;;cllolloxOO00xodkddkxdkOkdollooccc;,,';d0kl;''''''',,;:lONkc;;lddooollcldlclc::okOkdllc;,;;;c:;;;;;;;;coddddllodk0OKKkddkdldkdoodk
dc:::lxocoddxxkxdolodxxocllc:llccdxc:lc:lolcc;,,lOkl:::c:',:c:;:oc,dkdoooxOO00OOOO000kcoOOxddollool,.'';ol:c::llllc;:cccoxxdollododkk00xxdolc;'',:;;;,,;:cccc::cldkkdxdc:coxxoolloodxkOOxxkxdxxkOOolooloxol;,,,,l0Oo:,'''''',,;;lxKNOc;loodolc::oxolc:::cclllolccllc::c:c::lollcclokOxoooodO0kdllxOkxxxxkkdx
:;:cooccldkdx0Okxocoollcloolclcoxkxooxl;:lcll;'':odo;,col;';cdxc;,lOxd0OxO00KKKKKK000x:ckOxxddkkxo:'';lodxddccddkkdclolcckOxocoolllddddoddc:;;;:c:;;;,,;cccc::::lodxdloddooddoolcloddlldxdkkddxxxxoddddodd:,,,,,o0d:;''..'',;,;:cx0Kx:cxkO0kolcccc;:::;;::cllocokOOocllllddldlccclok00kxollooldxdO0OOOkxkOxd
;;::llccclddxxdooc::;:coxxdllokkolllll:,.,:lc::,:lllc:oxddo:,lkxc'cxdxO0OOOK00OO0O00K0xcoO0OO00Okc''coxkkOOxxxxddoodxOkdldO0xlc,,;;;:;::lol:;;;::::;;,,;:cccc:::coooooxkxdc:clooooodooxxxxxdkOOxxxxkxxxdooc,'',,lOkc;,'''',,,,;:clxOo:oxxOXXkoccclllolc:cc::c:cloooollldxkxkkxc;:cokxdddkxddox0K0KKkolodxxdo
doolloodoc:cllloc;llccloxxdkOkoc;;;;,,'..';:;;;,;cccloodkOkd:,:l;'cld00kxdxkkkkkddxxdOkldK0OOOOxc,;:oxxkdddddokxodxdodddkxxkxoc::c::::coolccc:;,,::;,,,,;clllcc:looodOKkooc::cccodddodkOKKX0kkOkdoolccllokxc,',;:k0l;,'''',,,;:::cdxolooox0XXKkxxdlolclc::::clooooxdlodkOO00xol:clcllooldxxOOxk0K0xoollodxoo
kOklccoolodl:;:;;:llododooOXOoc;:l:,,,,'.,;;::;,:lccloddooxxl:,;,,looxkxxdoddooddddxkOocx0OOOOx:,codxdlc:lookOkxxxololldkxdloddlccclocldo::::;,;;;;;,,,,;::clllclodddxdlcc:;;;;::cclok000kO0kkOdlccllood00ko;'';:d0o;,',,,,,;::::lokkkkdldO0KKkddlccclodooolllllookkdxxOKKKkl::ccc::odookOOOKKOkOkoclccoxxod
00OxxOkdodxxollc;,;;:ccl:cxxlclclolc:;,,,,;col:,;c:::c:;;:cllc,',;d0kdxkOOkkOOxxxxxO0kcoKK00kd:,cxdlc:::cododkxlll::ol:ldocccloollclolcccc:;;;;cl:;;;,;;:;:lllolldxdodxddd:;c:;,;;;cx0KOdodkO00OkkOkk0OkKX0xc,'';okl,,,,,,,,;::::ld0XKkodxxxdOxodl:c:cdkxkkxxkkxdxxxxdox00kdlccllooc:cdxdxdxkKKKOkkoc::lolok
xddookkddl:cldxd:;:;;:c:,;c;,ol;:::cc;,;c::oxl;,;;;::;,,,';:;,.',';okkkOkxxdxOkdooddlclxOO0Od;,cxxddocodloolldOxxxl:lddlccoddxOOkOkkOxcclc:;;:cccc:;,;;;::lolldxdkOxddO0OOxddc;:clccdk0Oxkkk0XXXXNNK00OO0K0ko;,',:l:,,,,,,'';:::cld0KkddxdddxOdodddxd::odxkddxxdooooddddkkddooodxdddolx0OkkOxxkOOkkdlccclcox
ccllcoddxxl;;cllccol:lol;:c;,,;;:ll:;;;coddddl:,;lc;:c::c;;:;,;cc;',coxOOOkolodddddl;;dOOOdc,';okkolcloddooodkkkddxocloocclodxOkxkOOkd:;;'.,;clc:lc;,;;;;clccclolcodddddxkO0kxdlodlldxkkxkkONNNNXNXOkO0XKxxkkl;',;::;;,,,,'',;::clONNKX0kxxkOOkkO00KKdcccllcclooodkOOOxxdddxxxxddddddodOkodO0OkkOO00kkxlccll
ccll::oooxxl;;:oolodllxd::lll:;;:c:;,;:cddoodd;':lllolooolloc,;:cl:,;cdxddkxddxdoc;,;lkkdc,',:lod:lo;oxddloodk0Ododdololc::codxxdkkxol:,''',,;:::oc;;;;;;cc:cclddllolollccx0kxooolccoddkOKOdkXNNXOx0XNNXOxlcdx:',;::;;;,,;,,,;::co0WNNWN0OOOkxxxxkO0kdddxdl::ldk00OOOOkxddOOxddddddxOOdOOxdoolodxdk0kxdlldol
lc;;;;;;:colllol:colc:cc;:llol;;::;,;ccclllodd::lldOkkkxxkxdc::cllc;',cl:,:c:;::;;:ccdxc,',:lllo:cxllxxxxxodkOOkxooddooc::cc::cclldkxdl;;;;:codxxoc;;;;;;::::cloddxdodoollkkoc:coodxxxx0XNNKxx0KOOXXXNN0dxxoxkl,,;;::;;,;;;::::::oKXOKNNXKKOxkkxxOOkdoooxkxddookK0xoooodddddooxddxxk00OKXK0kdoloolodlcolcodo
cc;;,,,,,,;,;loc::ccc;,;,;::::;;,,,,,;ccoodxxl::odox0Oxllllc:,:ooool:'';cldoc;::;,;c;;,'';oddxdccdlckOkkkdodkOkxdoooxxxolloooccc:cxklllc:clclxxxdlc;,;:;,::::ccldkOkddoox0KkxdoodxOOkkO0KKKK0dokKNNXKXKKKKX0xo:,,,;::;;;;,,;:clllkKkxOKKKNKkkkxdoxxlccodddxxxdodkOo::lodldkolddox000KKKXXXNX0xllllloloxdlxkx
',,',,,,;:;,,;cccccl:,;;,,:;;:::;;;:c:;:lolllc;:oxxdddoll:;;;',coooolcclolc;:ccc;,'''.',cdkxOOl:lcdkkkkdoxOOO0OkolccldddxxkkddxddkOkollclc::cc;:lo:;;,,,,:c::cccdkxx0K0kkKNXXKOkkkKKOO0O0K000Oxx0XXXKKK0XXX0ko;'',,;;,,;;,,;;cxO0X0olxkxxOkxk0kxxxxddkkkkkkOOOkddkxoo:collxkdodoxOOKKKKXKO0KX0xlldddoldook0O
..'',;;;:;,;,;:ccc:;,::;',::;;:::::lolldocl:ll:cxxkkoodddol:;;;okdlodol;,;coxoc,...''';:ldO0Ol;;ckK0OOOkxO0OOkkkkxdoxOOO00kkOO000Oxkxolc:;;:;,,,:c::;,,,,:l::ccclkxokKKXXKOkkkxO0kk00KKKXWNXXKKkokKKXKKKKXKOo,..',,;;,,;;,,;,cOKKKOkxodkkdoxkxk0KKKXNNOx00OKXK0OkkxkOxxkkxxdooOK00kOKOkkkO0K0OOOO00OOdlc:ldx
',;,',;;:c::cllcc:;;:ll:,,,::,,,::::ccdkolodxo:;lxdooxkxxxdl:;::clllc;:cdxoddc,...';lllloxO0dccl0XOO0OOOO0KK00OOkkxdxO00XK00K0000xl::cc;;::;;,'.',:::;,,;co::lcc:dOkOOkOKOxddooodddxxkKNWW0kkkxxoldk0O00Okdc,'',;;;;;;;,,,,,;lkKX00OxdllodkOOkOKNWWWWWXKNNXXKkxkkdodkkxkxdddxO00kxx0Kxloxx0KXKOk0XOkoclollll
,,,,,;;,;cldolcc:,,;:c:,,,;loc:;,,:c:cllloloko,,ldl:cxkxkOko;,;:loc;,:xOOkddc,'',;:coooxkOOdc::d00000OdoxkxdododkOOxdkkkOOKK00OOkkkdccc::c;,:;,,',:c::;;:ldlcc:::lxk0NWNNKOO0Oxdxxxxxdxk00xddolloollxO0KOo;'',;;;;,;;,,'''',:dOKXK00Oxdc:oxxoddx0NWWWWWWNNNXKKOxdollkOxxxdxO0kdxOKKK0xdddddx0OkkOXNKxloooooo
;,,,;;,,;;:lllcccc:::c:;;;,:loc::::c;cdldxoooc,;ldlccldxdxdc;;:odl:dOkkxdxo:,,;clol:c::ldddc,,;dO0OdkK000kdooddodxddoddoldkOkdlcclddlldooc;:;,,,,,cl::::clolll::cldxxkkkOKK00KKKXXXXK0Okkxdxxdddk00xldOx:,',;;;;,,,,;,.''.':ok0XK00Okdooccodox0XNWWWWWNNK0KOO0KKxooloxxdxdxkxocldkxk0kdllxkdxkO0KXX0Okxoodxx
;,;;::;:loo::::ccccoddl::;,;colllc:cl:::lkOdoc;;lxdccoddkxc;,;cc:lxkdldko;,,:lccdxoccl:cll:,;;clcllck00KOoloc:oddddkkdooddc::cclooc:::ll:;',,;;,;;cl:;;;clol::;;ccodxOOOxdxxxkxO000OOOOKXXNNX0kkxxOKxc:;,,;;;,,,,,;;;,''',;lxxOKkk0kdodoodlldOKXNWWNXK0OOOxxxdk0kollldddollolcclxOkOOdoc:cl:cddxOKKOkxdxxk00
:;,,ccc::col:;:cllokOkoodl;,:llloccollddo0KOkl;:oO0xododxo:coc::d0Odddlc,',:ldddxkxoccol:;';ccoocldkOOkkxdddoooldxxolodddl::cccll:;;,;lollc:::clollc;;;;cllc;,,:c::loooxoloxxkO00Okkk0KKKK000KXNX0xol;,,;;;;,,,;;;;;;''',:dkdoxkO0koclooxO0dclkO0NWNK0kkOkddooxkxdl:ldlloxdooloocldkOdcllcc:;:cokOxxkkkkkOO0
:cl:;:cc:cdxololcldxdolloo:,;oxxddkOkdxdoOOkOo,;coxxooooo::llcxK0xolol:'.,codolollccllll:',okdoclooodxddxxkxdo:cxOxlccldoddllclool::lllooclodooodolc;;;;::cl;,;:cclllolc:;;lllkkkOkxdxOkk0OkkOKXX0d;,,,;;;,,,,;;;;;;,',;lxxxdodoooclllxOOOkxdccxOOKKO00xxxdodollldxddxxxkxxxdxkxllkXKOxdc:cclddoldkkkO0OOkkO
loko;;::coooodo:;cllolcldo;,;lkOOkkOOxdclOOxdl,;codc;,,;,;c;;xXOoooc:,.';dxccc::c:;:::l:,,coooxdlclolodxdxkdlc:lxkdxOxoxkdl:;,;::c::lccodooodxxol:::,,,;:;:l:::colcdxddxxc;ll:cldO00KX000KKXNKKKx:'',;,;;,'';;;;;;;,,;cxOkxdloxxookOxk00Okkkkkdlddddooxkk0OkxdolldxxddkxxddkxdxkkdkKKO0Ooc:cooooloxxdxdxOkdo
::oocoxoododO0kooxOkkkddkd;,;lkOOkxxxdl;;dOkko,,oOOl;,,;;;,;okxl:cl;..';dkoccc::cc:clcccoOd::odolccllodlldddxdoddxxxkOkxdoc::,,,:lc:cccccoooldxxxdl:;,,,:;;:cc:ldl:xXN0xO0OkxlcdOk0XNKOdxKXNXK0o;'',;;,,,',;;:;;,,;;:odONNKdccldxkO0OO00OO0OkklcclllloddxkOxxxxxdxOOxO0doddddkO0OOkOOkkxloo::codoodlcdxddoll
dxkdodxkOOO0KXK0KKKXK0kkOd:,,lxkxxkkdoc,,lxkkl,,ldl:::;;,,;okocclc;'.;lllc::;;ccc:;:oo:;x0d::cllol:ccccclooldxddloooddoccc:cclccoddxo::cllclllodxdl:;,,;::;,::::odloOXOdkOxoodloO0KX0kxdk0KK0d:,,,,,,,'',,;:;;;,,;coxOxdk0kkdclddoldxO0OO0OkxoclxkxodxoxOk0kddoodxkOOddodxxkOO0KK0kxO00xolccclllllllclolcccl
k0OoclloddxxdkOkkOO0K0dlxkl;,:oxxolool:,':llc;':xo;:ll;,.'ldl::cc;'':ddc;,,,,;;:ccccll;:k0xooc:colcloc;;:lodxxxddxdxxlllloxxddooooxOxc:::loolcoxollc,,;:c:;,,;;;lxocldccddc,,cl:lkKKxoxO0kkd;',,,,,,,,,;;;::;::;:oxOkxxl:lxkkoodxxodddk0KOkOOxlldkOkdlclxoodlcccccclolcclllooldxkdlxOO0XXxxkoooc:cclllllc:cc
col::c::lc:;:codddxkOOddxOOl,;cddccccc:,',;;;,'ckxoxdc;,;looolll;''cdxxkdc;,;clookOxxo;cdxkxxlccdoccldodolldolddxxxkkkOOxdxolcclllodxl:::cll:codxkd:'',;:;,,,::;cxd:lo;;xxoolodod0XKOk0K0o;''''',,'',;::;;;:::cok0KOkdloo::llllodxxxdxkk00kxoc:ldoodxd:;lldddxdoc::;;::clc:ddllcc:cloookK0K0xdxdlcc::llolccl
ccc::;;,,;;;;;cdxkkxdolldkko;,;co:',;',,','',,,oOkkkl:coxkxollc;',cdddokkdl:cddoddxddl,,,:x0OOxxxo:;coddlloxkkkOkkO0KKOdc::;,,',;;clc:;:cll:;:cokko:'',,;;,,;:c;:dxl:c,:0NX00XKkkkKXKOkd:,'''''',,',;:;;;:::cclxkxxxOkloOOkOOkdodkdlloddkOkdl;:ooccclo;,looxdokkololcl:;c::llcc:;:ldxl:d0O0K0doxkxoldolloddd
ol:clc;;;;::c::loooodxdoloool,,;;,,;;,',;::cc,'cddol;:lclolllc,.'cdoxkxdoxdlcool::ccc;''',:lloddoldddoc::lxxxdxkOxk00kdolccll:,,;:ccclcclc:;;:coddl;'',,;;;;,:c::col;;,;kNXkdOXOxxx0XKd,.',''',,,',,,'';::cokOllxddxdxxdx0KKKOxlcxxoloooxdkxc:odoll::ll:;cldolxkxxxxdl,',,;;;;::,:ldxoodoxkxdlcloddxkdlloooo
ccllcc;,;:;;clllcloxkocoddkxo:'';,:l;;;:cddoc,;dOdl:,;codoodo;.,ckxdxkdccll::::lolcc;''';:c;,:ol:codoc;;llclclldxddxOkololccc::cccc::coddo:;;:lldxo;'',,,;c:;:cc:::c:,',okkOkkK0xxdk0o'.',''',;;,,'''',:cok00XxcoOkxddkkkkkOxooo:ldo:;ccllolcdOdclooc:ldollc::clloxoc,,;,,,,,;::;;::cclolooc:c:cdkddo::ldooo
ll::cc:;;;,,:::coxkdol:::codkxc,,,:c::;;:ccc:;:xkl:;:lldxlol;,,cddlcool::llllc::::ll;',cc:lc,;ll:;;col;';lc:;;;:ccldxkkdxkxolcoxdoo:;:clllcc:;clclc;,'',,;ll:;:c:;::::,;:lxOOxx0X0dl:'.''...',,'',,..;cdkkO000Oo:lol:cloxkk00xlc::dxlcllc::;;ldddoll:;:okxl:;:;:ol::,',,:c::;;:,,;cc::;,;:;;::;:codo::oxdxkO
,,'',,;;,''';:,;locc:;:c:okO0Kx:;;,,,;:::;:ll:cdl;;,;codolc;.,:cllodlcccoxolol:;;;::'';ol;:c:';:,,;;ccc:,,:c::;;cloodkkOOxdooolllc:,',;;:clc:cl:;cc;,,,,,;coc;:cc;;:lc,,,;dxkxldkxl,.''''..','''''',lxkkOxxOOxkdc:coc;::oxxkkdddoclxxddkdc:,,;:lxo:;::oxdl:;,:c:c:;:lc,,ccc;''''',,;;;,,;:;:c;;cllooldkxoddd
,,''''',''''..'',;;:clddllxOdlloddo:,,;:cllcc:cdo:,,:lcoxdc'.,cc:lloollccol;:llc::;,',;c;:clc,',;,;::cll;,::c:,;coollldxo:lo:::cc,,:c:;;:cc::ccllcc:;,',,,;ll:;cc;,cll;,,':looc;,,''''',,,,,,'',,,cdxkxoddokOdddc;cxdcccodollclkkoclOkxxooc;:;::clc:c:coccc::lo:;;;:c;,cxd;';;,,:l::clc:::c:;:cclooooxxooddo
;;,,,,,'',''',;',:llc:lolllccloxxdolc:;,;col;;:oxl::c:coo:'.';cclooccclc,,;;;codxxl,,clc:cccc:;;;;c:;:c;,,:clc:lollllcol::cl:,:c;;cc:;;c:;:lxxolodo:;;,,;,,lo:;:c;;;;cc;:,,lc;;,''''..,,,,,''.';cdO0OkkOOOO0kol:,;:loooooll:lddddxolO0xlcl::;,;cc:;,;;:::odoollc;,,;cccoo:coxxc:cc:lcloodxooccddc:ooolcldxxk
;;;;cl;',;;;;;:;:llldooddc,;clll:;;:cc;,;;cc;;cxxdl::;coc,..,codxkxc:;::,;:c:ccoxdc,,:::lol:;;;:cc:::cl:,';clc;;;:c;;ldolxkxdooc:;;;;:;;:::lllol:lc;;;,,,,,cl:;:::;;;:l:;:::;,,,'''''',;,,''..':xK0ddkkdoxkOkdl:::;;lkkdoxxdxxocoxocdkklcllc;';:::loodddxdllllll:;:odc::;;cxOxc;;:oxl:cllldxkxxo;;cclc:codxk
',;;cl:::cclddc:ccclxxl:,,:ccldolddooll::;,,,,:dOdll:;odc'.,ccdxddocll:;coc:::;cc:;,,:lldxko:;:clc::;:cc;,;;,;;;:looddodxkkkOko:,;;:loll:;',;,;:cl:,;;;;,,,;::;:::;,,;ll:::;,,,,,,,,,,,;;;,,'':kXKxlooocokOOdldxxoc;cxkkxxxkxooooxocdOOxdkOxc:lc:ldodOOkkoodlc:clccxkddoccccdko::lkOxd:;:ldkkxollcll::cllcld
'''';;cl::clxko:c::dxl:,,cddllloddk0Okkdc,,,',;cddllloko,.,lllkxc;cdd:,cdo:;:lcc;',,,ldddolc;cocc:;;,;lc;,;:;;coolokOklokdxdoddc;:ldxdoo:,,',,;::cddl:,;,,,,,,;;;;;,,:ccc:;:;''',;;;;;;;,,'',:xXNOlloddld0KOOO0KKko::odddddxkkOkoddoOKX0kxxx::cloxkoodlloc:oddooddxOKOolxxclccol;ldddoolloddxxOOkxoc:cdOkxkd
....',:c:cc:lo:;c;;lc,;,,:ccloclodxdxddoc:,''',:c:ldlll;',oolOKkdoll:;ccccloodolc;;;;oxddo:,;ll:;;;:clo:,;cc;,coolcdOOdloloc:clcclloolloc:,:cllccldxxo:;,,,,,,;;,;;;;:c;;:;cc,'';;;;;::;,,'':d0NKdxkdxolkK0OO000Kko:,cxxdddkOkOkoccdkkxoollc;:coollllloO0xoccloxkkdokOxololc::::;cok0Okkxoooox00OOOkxdok0KNK
.','''''',;,:o::ccc:,,:;;;:cokxxxxdllccccc;',::llldkkc'';dxloxddkklclodxoloxddo:,c:;:dkkdoc;cccoolc:;clc:,;cl;,;:ldk0KKK0Od::cclloddxkOklllc:::;,:clol:;,,,,;,,,,;;,;;c:,,,;;,',;;:cccc::,',:kNWKddxloolodxOOO0OkOkl:lxddkxOOkolc:;ldoclllc;;;;:looollxOO0kocc:ldkdloddollodxc:::oOK0OOkxddc:ok0K000XKxokKNX
',;,'.',,',:cc:;;::,;oddkOOO0K0dodxxc;dxxc'.;oxddxk0Oc',oOxc;clxkxlcdxkOxoccll:,;dxoodddxo:;:coddollc::::::;lc:coxkkO0Okool:;clooodxkxdo:::;;;;;;;cc:::;,',;,,,,,,,,,;::,',''',;:::llc:::;,;cOWWOollloxolclkkxkkxxxxolxxdddddoccl:;:c:cccoo::cllolloxxxxdOOxolllcloodxdl:lolooddlcdOKOkkxdxoclxkxkkOXNXOdx00
,'..''',;,:c:;:,'',:cdddxkOO0000O000kx0Kk:',;ck0kxkOo,'ckocllcckOocoddkkdoolc;,,cxOdlc:;:;:c::;;,;:cl:;;;:::::loddoolooccoxdoxkkdlooxkxxl;;;;,;:clddl:;;,',;,,,,',,,,,:c;,',,,,,::colc:;;;;:lONXdllcoxdoclodxxxxkO0Kxccodl::;;;;::;:lc;:lc::c::olcloocclodl:cccllccccllcclllccoxooolOKkxO00Oxxxxddxxx0K0Oxdo
'...'''',,;;'..'':ll:llodoxxdO000000K0Okc''';;coooko,';odllxdoxkooxdooddooolc;;:lkOkxdddllolllc;,,;loc::cccllcc:::cokkkxxOOddk0Kkxkkxddxxool::,';ccclc:;,',;,,;,,,,,',;::,'',,',,,colc:cc:c:o0NKdllcccoxx0Kkxxddk0XXOxo:cccolc:cc:;coolodl;;:;;cc::::::;;cldxdclocc;;l:':odoccddllxdlxxdookkloocldxkkddodOOo
'....,'..,;,''';,,::;;;:okO0kxkkxkkkkxxc''''';c:;dk:.,lxc,;cloooodxxlcc:;;:;,,,;lolldox0Oolodolooccdxdlc::::::loxdook0OxxOkooddkxxxo::ldxxxl:;,,,cdoccc:,,;;,;::,,'''',;::;,,,'',,:lc;:llll:xXXkc:lo:cldO0OkOkkdkKKKkoxo::cool:;;;;:c:clloccolc;:;,;;;:;,,:dxl:::cc:,,,,:c:cllll::colcc:odkxdxkxdO0OOOxdoodd
',...,;'':c;,'...';;,,,;codxxolk0xollol,'''';::;lOo'.;dd:,'';,,;;;,,,,;;:::,.'',''',',,;,',,,;;::;;,;;;;,;cook0O00kloO0kxxdocccc::cc::cllll:;;:c:col:::;,,;;,;ll;,,,'',,;::;,,'',,;clc:oxxlckKXxoccxooddk0kkxokkOXXX0xoclc:;coool;;cc:c:cxkkkxdoodolllc::;;;;;;:,;;,,'.';::;cdoo::c:clccllxxkkk00OkOO0KKKkoc
;;'',:::,;;,......,;:ccoxolokkok0kdxkd;.'',,::::ol'.';cdxoolll:;::cooodxkko;,;ccc:,:c,,;;;::;;;:ccclllooodkkkO000K0kodkxxdolol:;;;:::cooc:c;,;clllol:;:;,,;;;;co:,,,,',,,;:;;,''',,cxocoO0xxk00doclxocxkxk00Oooddk00kkxolcloccclc:colcl:;oxkKK0kk0kolcccc:;,,,'''.',,;,',:clddol:lolc::c:cdxoodKN0kO0KK0K0kx
:;,,'.':cc:;,,;:;:ccloldkkOOkdloddkkkc'''';::;;lo,.',;ckK0xodxxdkOOkkxddxo;';:lol::cdo;;cddololcllloxxdlldxxkxdxdxOkclxxolldxolcccol;:llllc:::llllc;;;;;,;;,;:coc,,;;,,;;;;;;,..',,cxdco0KOOO0d:clclclk0kxOOkxdOOkk0kO00OxO0xxo:clldxdocloooxkOxxkxc:;,;;,;::;,,,'',;:clddxxl:ldl::cc:;c:;cdxodOK0OOxxkkO0KO
:::;,,,:oolc:;:oxxool:lxO0KKko::cdxoc'.''',:::coc,,,:c:lOK0xddxxkO0Odccodc,;cclodl;:lo:,,::;;;;,,;;cokOdlok0Kkxxdxkdlldodxddxodl;:c:;:looddooccc:::;',;::::;:::c:'.,cc:;;;,,,,''',,:odlo0K0kOKl,coc:ldxddkOkkxloOKX0OkkkOO0XNNKdc:cccdlcoollodxoldkoc;;c:,,;,,,;,'',c:;colcl::cc;',cddoldl;:llxOO00xldxxxk0k
:',;'';cddoc;:okOkxOOdoxOOOkxl::cxkc'..'',:clol,.':oddco0K00Odoxxxdol:;c:,',coollddoolc:;;:;;;:;;;cccldooxkOOkOOkxlloccddxkOdccl:clccoolccoc::cdl;,;;clc:::;:cc:,'.':lc;;;;,,,''',;:odook00OK0c:dOxxkxl:oKXXXKkdk00OkkkkOOOKNNKxoc:;;ooc:,,cclolccldc,;;,'''....'';c:,;:cc:;;llc;,::dOxxkl:lc:ldOOOkkOkxoodx
oc;:;,:clodxodxkdxOOxdddxOOkxoodoo:'''..;okOkd;.':odkocdkdllxxc;coocc:;;,'';ldoldkOdoll::;;;:;,;,;:;:loololoodxkOOxdxcckxxKOxxoloxkOxlc:;cc;;:loc;;:oxOd;,;,,;cc;..,:ol;,;;;,,,'';::llccdkO0X0ooxxxkOkd:cxO0OKXKkkK0kddxk0kk0Oxl:;;,,;:ll:clc;cl:,;:c:,::;,'',;''';c:;col:;;::;;,;:;dkkKNXxll::cddd0KKXOddxk
ccc:;coxkkdoodxdooodxxkkdodllolc;,'.''.,ok0XOc'':okkl,;:locccol;coddol:'';:cllc::olcddooc,';llc,,:cllddodolokkoldk000koolxKKKX0kkOOOxocclc,',:cc;;,,:okd:;;,',:c:'.,:oo:,,;,,,,,';:;:c::lxk0XKxdxdokKKOocdkkk0XKOooxkdcd0OOkdo:lo;',;;;;coxdl::c:::cxdcol;,'',;'';:,,;:;;:;,,',,',,cdlo0KXNx:;;:lxkk0XNKk0KO
;:ll:coodocccllc::looooddol:::,'',;;''.':lxko:;:oxOd;;:ldkdc:clloxkkx:..,ckkoc:;;''ccldl:;,,:ol::llcclclkOkdoddxxddxkxoldOKKK0Okkxddolc:;;,,;:ll:;;:ldxo:::;.,:::'.,:ll:;;::::;;:c:,:c::cxO0XX0xooookOxdookKXKOOOxox0xcdkkkkdccoo::l:;;;;;clddodxxdxxollclc:,''';;;;;;:;,;:l:,,,'.,clccd0XKOo:;:dO0kdkK0O000
ldxd::lldoc::::c:;:;;c:col;,:o;..',:,.';coo:,;:;:clddocoxkkxkxoolddl:...,oxl:clc;'.:ooxo;';,,;;,,:oddxloddxdodododk0Od:;o0KXKklcclcc:;:lc;:;:dxkd:lxxool:;;;',;::'.';cc:;,;::llccc;,;::;:ok0XK0koccldkkxko:okkxxkkdoOKxldxxxxlxkc:oxo;:ll:;ccldxkkl:ccll;;clc;,;:::clcl:,,;lol;,'':lcc::lodO0x:,ck00OdokxxO0
ldkd;:dxkkocloddc;,',llclc;;cc;...','..,col;';cclcoOkxolooodoccocokl,..',cl:;;::;;,,clol:,:cccc;,;ldxxl:clclllc:ldOK0xc;lk00koccll;',::lddoloxxkdclkOkko:;,,;:;::'.,;:::;.',,cdc::;,;c::;clk000kl:coddooxd;:xkkkxolcdOOxkOkkkddxllxkxc;oo:;::coc:cc:oc:c;,:::cc:,,;:lc::;',;:c:,.'cdOdccldOXNXk:;oO00Odlldk0
k0Oo:dOkxo:,;cool;''';::c:,,;::,''''',',::c:;:llcoOkkkdxxodxxl:cldxc'..,coxolcc:;:,';codl:ldoooc;,:doc;;clxkdc:;ldxkkxo:cx00kdxkxdc:l::ldkddOKOOdccx000xc;,,cc;:;'.';:c:;''',col:;,;:ccccc:lkO00dclkOxlldl,:k0XNKKkolokkxdk0X0lcoxddko::cl:;::c::clollclc,';;cc:,,:coddooc:ll:cc;:oxO0kkkdx0XXKd,:o0XXKxdddk
okxc:oxOko:';:cccldl,';;:;'',;:::;;,,;;',;ll:;;,'coodxooooxxkdc;:ccc,',:lxxolodlld:.,:dkxl:llc;;clllc;,,cokkOOOxkKKK0OolldXKkOKK0OdoxxccxkookOkko:;oxxxo:,,;c:;;,'.':loc;,,,,lol;,;:ccccclccdkO0OxxkkOkdo:,:x0KXXXOdoco0xlkkkxc;cxdlkklccc:ldl:lkxolccc:c:,:::c:,;:clooc;,,;ccloclocoxodxoloxkkdc;:dOxdkK0Ox
loo:;cxOOOdoxdlodkxl;;lol;,,,,'';ccc:,...,l:.....':okxodkOOxOOdc:,;::::loxkoc:::c:,,:cdxd::lccc:;:cll:;;okkk00OkkK00KOdocoK0xKXK0xc:okddkOxokKOdc:cdkxdl;,',::,,,'.,;ldc;,,;:loc;,;:cccccllcoxkOOdd00000Ol:lxkO0kxkocooddlkOxdc;cOOddOxl::cdxdooodlllcol:lodlcl:,;;:ll::cl:;:coxocccddodkxodkOOxdl::ll:oOO0O
doc,,;ldkOxdxxxxxkko:oOOd:cl:'..';:lc'....;,',;'.,oOOxok00KK00Odc;;coocldxkoc:;,'.'ccll;';lc:cl:,:clolc:xOO000OxxOkddookdoKOxKXXKxdloxoclOxoOXKdc:codool:;,;::,,;,',;ldl:,';llol;;;:cc::cllcdxxkOdoO0kkOxc::o000dlddoxxddldkkxddx0Oox00d;':ooodclolloooo:;:lcldl:;cldoccloo:cloxo:coxdlodoclooxdl:::::;:oxkk
ddl:;clok0kox0OdoxOxclxOkxll:,'..,,;;'...'cc:cc;;;c0KkdO0OKKkkxc,,:oOkoxkxddollc;';lll:';odddlc::ldddolokOOO00OdllcodolkOoOOxOXXXXXXK0xokX0xOXXKOolccloc;;;;;;,,,,',;ldoc,.,llll:;;;ccc:cllldxkkdlldkOkkkl:;:dOOkxdlloodd::lokkkkOOkKK0k:.'lolollc;cxk0Odc:oxkxdc:oxOOdlcc;:ooddl;cloocclc:dxdocc,,cc:;;oxkO
ccc:cd00O00xxOkoodoccclodo;,;;,'.'';,...:d0Okko:,;:dX0xOK00Oxko'';o0NOlllol:codo:;loc:lloxxkkoc;:okOkxodKKkok0OdllodxxdO0oxOdkKXKKXXXKXKXN0xOXXXOc';lxxo:;;;;;,','',,cdoc,..coloc;,;;colllloxkkdc;:odkkkOl:c,:x0OOxoddllc:,:dxxdoxOOOOOOl..cdollo:,dKXKK0xxkO0OdclO0OOkxdc;lkkOOoclodxdllc;cokkocc::odl:lOOO
lloookKKXXKkxxdccddcccloxo:',;,,''',..;cdk0kdxOdlxkxxllxkdxxdo;.,cxKXxc:::::ccoolodlcll::lcodlcccloddoc:xOOdccc:ckkdxdok0ddkxdldk0XXKXXXXX0xOKXXKdcoxxdl:;;;;;,,,..,;col:;'.:odolc;,',clldxxxxxc:lcdOOxdxkdl;,lxxkO0K0xoloc::ccc,cdocoxOd'.,oxdddc;lOOxdodxxoxOx:coollllllclxO0Ol:lldkkkdl::lxkxddxddOOdlloo
xdlldO0KKKKKklllcodlolldxo:''.''''.';cxxloxkccdook00xc,:lox0kc',;oOO0kl:c:;;;:lc;lddl:::::;:::cc:::ccc:,;:lolcloclodxocldoldoclxk0000KKXXXKkO0KXX0kOxodl:;:;;:;,,.',,colc:;.'colcl:,''';lxkOOkkdoxxoloold0Ol;,:ollloxocccclo:,cc''coolllc'.'lOOxololclccc:lolldl;;clol::::clxkolc:odkKOkkdlc:lxOOkdoodxxxl::
kOOdcdOkodkOK0Okclxoxkooooc,'''''',lookkddxxlldxxoolodolok0Oo;;codlo00dlddlcldkx::dkxoc:cl:;;:lxxc;;cc,;cclolccloc:cccodkd:c:o0K00000KKKXXXKKKKXXXKKxoxo:;:;;;,,,',,;cllc::;,colccc;,'';cxOKXK0kddddddllOXKkxl,:occccclxxldd;;ll'':lccclc:'.;kOlldxkd::olldxoc;,',;oOxlc:lkkocclldOkk0kdxdxkxk00Oxoccoxkkkl:
00Odc:::oolxO0KKdlddk0Okkdc,',,,,,okooxxxk0dok00KKOkkO0kxxko;,cllllclk000KK0O0Kk:c0000Oxkxc:cclxOxlcdxooodk0xlccdxdxddxk0k:,;lkOxOKKKNNXXXXXXXXXXXXNOkKx:;;;;;,,,,;;;clll:;cllolccc:,,,;lxOXNNXOdxdx00dd00OkOOc,lkOkdxxxxdxc,coc.';;;:lc::,.'ckxddoxxdoccclol:;,.,cokxdxddkdllcdOOxdookkOOOkk00kxkxdodxxkkxc
O0kddoc;ldloodkOkllxdxO00x;,,,'';lkxldkxdolcdxkO0K0kkkOxkOo;',:ccoOxcdKKK0kkO0KkcdKKKKKKK00Oddk0KOxkK0xxkOKXKOdcokOkxxkxdd::doodcdxoxOO0KKKKXXXXXXXX0OKx:,;;::,;:,,;;;clc:,:ooolcccc;,,:ldkKNNNOllloddddxxxxxd:'ck000kkxloc.'cc'.';;:lddl:;,',lxxdddxo::;,;loolc,;loooldxxxlloco0Odddldxxkxkkdox0XNX0xdOxdkd
Odldxdolcc:;:ccoolclkkdxOl,,,,'';cc:cx0Oxolk0kxxxkOkk0K0Kk:,;;:clkOdccxOkdlcokklckKKXKKKKKXX0O0XXKKKXK0OOOKXXKkddkOxoodollc:llldoxxlllldxxkKXXXXXXXN0O0x:;:;;c::c;,;;;clc:;,coolcl:::,;:lld0NNN0oc::coxxkkolcc:,,oO0OkOxloc.';,..;,,:oxolodc'';okxolododxl:xKKxl:;::ccccloocldloOOolxdloxOkkOxldkKNNKOdoxxOO
xxxkdlddodoc::::ldo:lOkdo:,,''',cc:;ckXKxokKXXKOxxkOKNKkxc,;clodxKKKOllkkoooooc,lxk0KKKKXXK0OOKXKXXKXXXKK0KXXK0kxdoddlccloc;l:cxxxxllllodxOKXNXXNNNNKOkd:,;;;clcc;,;;,:cc::;coolcc:::;;:ccdOXXX0xolokkkxddlc:clc;;:dO000dol,.,,.':;;;:;;codo,''l0kdkkxdxOkodxkxoooc:ccccc:;:dOdd00xldxllxOOxoloddxxxxkOdxOOK
ldxkxdxkkkxoddol;:l::xOkl,,,''';lc:;cOXkok0O0OOOO0KXXKko:,;oOOdo0XXXXOoloddodl,'coldk0XXXOxkOxdox0KXX0KXXXKKKKXKxoocl::cldo,;::lllcloxdooodk0XKKKK00Oxol:,;:,:llc;,;;,;clc:looolc:::;,;::clx0K00kkkO0xoccc:;',clc;,ck0O0Ooc;.,;';cccc;;:cclc,.';xOxxOkodkkxdollloodxxdodxocodkxdOKOxxolxkkxdodkkxddddx0klkKO
dooldxxxdlllcoxxdol:;lOx:,,,'',:lc::o0Kod0kxxkkxO0KKkolc;,:x0KOxKXXXXOxxl:ldd:,cdxddxOXN0ookOxoooxkxdooxkxdolldxocdo::ccldd:,::cllooooodooxddxdodddxdool:,;:,:ool;,;;,;cll::loooc;;:;,;:::clxOO0OddxOxddololclxkdl,,ldoodc;,.;;.cxdl;,:ccodoc'.,o0OkOxodolloool:::okkdxkOkddxkxokKkolcoxdookO00kdloxook0dlk0
Kxxkxdl::ok0OOkkkkOOocol,,,,',:lc;:cx0kxOXKKKxcldkOxc;,,,;ldO0kk0kkKXkkkdl;,c:cdddddoxOOOkxOOkkdodl:cdoclccc:clc::ldlc:;:clc;llclcccclocclddlcooolll:;;;;;;:,;lll;,;,,;:clc;coool:;:;,;::;:cdxxOkolccloodddddxxkxoc,,;cldxo:.,,'okd:,,:ldkkxd;.';x0OOxlcccl:;:;;:c:ldoooloxodOkdx0kdoodkkxkOOkOOxdxollx0Ood0
XOkkdl:cldxxkxxdodxkkdl,',,'';::;:cldxO0KKXNKd:;;;:cl:,,;coxkkxddoodkl::coo;;clc:ccccllodoooolodl::lcc::cclolcc:;coxxl:;:;::ckxcccodc::c:cc:::odl;,;;,,;;;;:,;lll;,;;,,:ccc;:oool:;:;,;::;::dkxxkKKxc;cc,;::codxxol:',:cdxdl,;''dko::;:okOoldl,.'cOkxxccdl;;lc,,:;:c:c:,:lx0OdxOolodkkxOOkxdoxxxkOdloodxxxkx
KKkddooxkxc:ldOOkxdxO0o,,;;,,;:;;;;lddxkO0K0d:::;ldlc;,,coxkxdkkxxkd::ccdkdc;okl:ccclcclcc:;;,;:cc::::lddxoc::loolcloc,,;::;:xdllcoddxoccc:;,;cdo:;ccllc:;,;,,:;c:,:c;';ccc:;ldoocc:;,;c:;;:dxddxKN0o:cc:;,,:odooc:ll,,lkOxdlc,.::clc;cdxoldxx:..,lkxooxkoccc:,;:,,;,',,;cddddodoccoxOOkxxxololokdll:coldkxo
00OxdlloollldkkOkxddOkc,,,,,;::::llod:okk00o;cdl:ldo:,,;lokkollodddlccloool::xkdxddxdllolc:'',:cooc:cldk0KOocloodolccc;;:coc:xxldolk00OOdc;;c:,;:cccodol:,,;,',,;:,:l:,;ccc:;cooolll;,;cc;;:ododxOKklloooooc'',,;:lxxdl:ldlllc..;;ldolc:lloxdl;..';dxld00kxooocloc;,;:::;;cloxo:cl:ckOOOxoc::clddollc:cloddd
0Okdlc:c::::cllooldxko;,,,',clcclxkkd:lxkOkoccldkkdl,';:ok0xlcldxdoolllxxlll;dkoxkxxOxodoc;::cloollloddk0X0dolccccoololloool:dOdkxdkkxxkdllloolcclcoxdol:,,,,''',:,;c:,;ccc:,cooooll;,;cc;;lddodxkOOkkkxxxl;''''';;::::;,:c::;..';okkxd:;:dkkxl'.',:dddxoloodkxxxoolcodddddlcclododollddoccc::oxxdddxddxkxoo
xkOko:;:;:::cccccloxxc,,,',cooodk0xkOc:xkkko:coO0ko;',;cdOkoolcokkddolldxddd:d0xdk0Okdool;;:clol::oddoxkOkooolccld0kloxkkxxxc:xkdoxkxoooolooxkkxdoloko::;,',;,'',:;;::;;:cc;,coodlcc;,;cc,;odoodxkkO0Oxdddxoccloodocl:;ll,,:;...':ookOo;,:oddol;..,;lxkxooooodxxollcclxkxxxxdoooollc:cldocc:cllllodxxxdooooo
cldOkdxkdoooolc::cldo;,,'';okkO0KKdcdd:cxxocddccloc,;:cdkkoloc:ccccdkl:clxkl:x0kdxOkxolllolodxxoc:ldldOOkdlooc;ckOkxxdodkkkkx;;oxxkxcldxxdoolcloooodxocc;,,,;,'''::;::;;ccc:;coodl::;;:lc;:looxxxxdxdodk0KKxoloddoo:;ccox:'lxc..,:dxxo:;:lol:,:;'.',:dkdooxkoloollllldxxdoc:dkolc::clcldxoodoc:ccodkOxxxdoxx
oc:cclk0Odlodxkkkxdo:,;,',cdxdx0X0o,:xo,lxdx0Okdc;,,:lldkkOOdlodoloOKOkxkkOo:xKKOddkxxdox0kxOxddlccldx0KkodxocccloddxkdcxXNXx:';oddc:cloolxxdl;:ldxxOxc:;,,,:;,,';:;::;;cccc;:lodl;;;;:oolcloxdxxxlokxONWWWXOxl:llccldko:;'.ll..':xdl:;cdkxdc;;:,..';:olcclxkkOkoloddkkxdl;:olcc::ccllol:;:c:cloxxccdOOxkOxd
xxo:,;lxOxodxoodxO0d;;,'',cdoclxO0Oc'co;;oO0OO0Oo;,:odoxO0XKklldkO0KNX000K0o;l0K0dl::lodxOxxdoolllllldkkxkkOxlooodkOkOkocxOxl;',:c:cllllodkKkolccoxdxl::;',;:;,,.';;::;;:ccc:clodc;;;;:ddooldkxdxxlc0XOONWWWWXxool:cldxolol,':,.';dl:ldxkxolol;;;'..':do:lokOOKK0xl:cx0KO:;ldlc:::cc;clc:ccllodoxkolokkodxdo
ko:;:c::ccoo::ooloxl,;,',:lddc:dkO0kc:lccokOxdkkc';ldook0XXKOdlxkxxxk0K0OOxc:dkddool:cooodxxkkdoc;;,,cdxkkkdclooddxOxoc:cclo:,'.;ccc::lldkkO0Odc:coxOxlc;,,;;;'''',;;:;;::cllclooc,;;;cddloodkddxkolOKOkkXWNKOkxl,:lodxooxxo'.'.,;loloxOkxolool::;..':ddc::coooxkxooxOkxc,cxdolc:;::,;;;lolxOOd;;coxxxolcodo
ol:,;ccodoc::lkkdlc;;;',cooxxloO0xk0xccl:o0O00Oo;;coccdOXXXKxodddoodocdkxdc,lKkcclodollclkOolllol::;,:clxO0xokOkkkko:::::;;::;';lldOdlllcloddlclccd0Xkc::;;;:;'''',,;:;;::clcccoo:,;;;cddloodxddxkxdkkdddddxxxxxo:loxxdl:okdc.';,,:dxocd0koodxxlll,.';;,;lodddxxlcdkOkl;':looooodoc:;,,:lcldkkdolccccclxOOOk
;;::collxdl:;:::clc;,,,:x0K00KXNOldOkc,,:x0000kc;lddlxKXNNXKOOOk0OxxxxOOxdl,ckdcodddoodoldxdxxkkdooolodoodxddkkkxxdl:coc;;;::;,cd::odccc:;codxxkddk0XOlc:;,;::'''',,;::;;cllc;col;,;::cooloodxdxkkko:;c::c:lxOkocx000Odclx0Ox:.:c'.:codddodOKK0o;:;'.''.,lodooOOolddolc'':odxOOkdlcllloollodkkOxllxxlcclxOOx
:;;;cdO0KOl:cl:,:c;;,';oOXNNWWWNx;:dxc,;ckKK0kl;cdxxkKXK0KX0kkddkxldkxxdooc':olcoxxlccokkxxxddddxoooooooolodddddolcclxOxollxl;,oOdc:::;,;cloloooodkkOkol:;,;::'''''';::;:cllc;coc,,;::coollodxxdxxxolllloddxkxookOkxxOOxdkOkxo,'l:'.'ckkddk0Okkocll;.',,colldddoclooc;'';:loodxolddlloxkdlxO0kOOkkkxddolooc:
lc:ldxxxdl;;:c;;cc;,',cxKNWWWWMNk;,cdl;cdO00Okc:odokKXKOO0KOdxooxdxOxoolod:'cxlclloolloddxddxOxddoooooddocc::;;lddoxkOK0kld0d;,dXX0dcccclddolodccodollolc;,;cc,''''',::;:clc:;coc,,;;;cooollodddxxxxddllxkOKdlkKK0kxddkkdkdlooc.,c;.;okKXxokOkdoodl:'.';odc:cc,,:coc,..,;cddlcccolclodxOxdxOOxddO0dcccloxkxo
lcokkdlcc:clcccll:;,':okKNNWWMMXkl,,c:,coxOOOd:coclOXXXK0KKxdolllokkdllll:,,oxloxdooddxddl:ldxdxxloxdxkxlcc;;;:lxkxxk0X0xdOKd;,lKNKkolllldododxoooccccllc;,;cl;''''',;:;:llc:;cdc,,,,,:odoolcoddxxxdccok0XNXodO0K00KXK0kllxoclo;.:l,;x00KKkd0Kxoxkdc,.',:oc,;cc;;;:;'.',;oxdodxdolloc:ldddO0Okxlcdxolloxkxod
:;cdxc,,:ccloxxOx:,,,cxOXNNWMWM0doc,;:',ldkOxc:c;;d0kxddoolldl:cddlllccoo;.'::;cxkxk00xodocloddxdldkdoxOxooloook0klcoxocoxdoo:,cOKOollldddxdokXXOdol:ldoc;;;:l;.'''',;::clcc:;cdc,,,,,:ddoolcdkxkkxdox00XNXOoxOkk0KXNWN0oclooldo,,l,:kOxk0OddxoxKKxc:''';odc;;clddl;',::cccldxxoc,:dddxkOOkkxxxlllldlcldxook
;c:;,''.',,,;coxo;,,:dkKNNNWWMWOoko',c:;lxkdc;;;,ck0ddkdc;:::ccloodkolool;.':lccldxxxdoxxc;;:cclldxxoodxO0xlox0XXOdl:;;;cocloc;:dO0OoldkOkxk0O0XNNXKxolcc:;;:l;''''',;:::cccc:lxc,,,,,:ddoollkK0K0kdlldk0KKkdONN0kOKNWWNOllocoxd;';,;dO0OkOOxccok0kdc'.';:ccodkxxdc;;;clcccc:cl:,':oxkkxxdxxdxxolc;ldxxxdlld
;,'....''',..,;,,,;:ox0XNWWWWMNd:oko,:dloocc:,,,:d0Ooodo;,:::cc;lxxdollcc,.:llolldxl:cdxdlc:clc:clddc:lllxo:;cdxxxkOxllcc:cl:;;;oOkxkkxkkdoloxO0OOKKOdllc:;;;c;''''',,;::::::cdxc,,',,:ooolllOXXXXkx0OxkOOkdd0KNWXK00KNNklxx:;ll:;,.,lk00OOOxcldood0Oc'',;:loodkd:,;;;coc::lc;;;,;;codxdlcloooxxo:clcdkocool
''....''''.'''.'',;coOKNWWWWWMXo;;okccOkdoc:;,;;cdOkol:c:;:coolllllllcl:,''ldlooc:lxdllldxlcolcclcclllc;cldo:c:;;:cccc::clllo:,:lOXKKXXXOddoclxxxOK0kdlc:;;,;:;'''',,,;;::;::cdkl;,,,,:oollld0NXXX0x0NNWWXOodOOO00KNN0OkdoxOxlccloc',okxkKXX0dok0Oxdxo,.';codoccc,;llclcool::c:'';;::;:lclodcodo:;ldo:lloxdl
...'.....','''',,,;cdOKNMMMWWW0o:cdkolOkoo:,,,,:ldkdc:;;clc::lddc;:clccc;.;ddodllclkxdlc;:lodlc:;;::::,';;:c:;:l::lc;:::coddd:;ld0NXOxkdllloolodoOX0Okxl;;,,,:;''',',;,;:;;:clxko;,,,,cdoc;lk0NNNNNkONWMWXkllx0XK0kOKKOkOOkkkdol:cl,.cxdldOKOxkd0WXkoc'.',:lc:c:,.,cccloodl::;'.',,,'':ccloooddllddddlcooolc
'..'..',',,'...',;cdkO0NMWMMWNOdlcdOxkKOdl:,,,,cloocol;,colcoddoolcloldd:',ldxddookOO0xc;;cddccc:cc;;;,;,;;,,:oxo:;;::ccoodOk;,dKKOdooc:lolxOdlllONNXKKd:;;,,;,',;,'';;,;;;:lodxd:;,,,cdo:;cx0NWWNNOONMMMX0XKOkxxOkdxxxxOOO0X0ko:;c;'ldloollodkdok00ko;..';colc,.';:cc:cclc;,;;;,::,',;,;cdxk0Oxxxdoddo:;;;;
....';;,,::;'.',,:oxxkXWWWWWNXkdxllddddxl;;,,,;clc:coo;,;c::ll:;;;codOOdl,':odooolx0Oxdoccdkocllcc:,::cccollloddxo;,;ccloxxOo;:odooolccllodxodKK0XKOOKXx::;;,,,',:;'',,,;::cloodo:;,,,cdo:,:dOXWWNN0kNMMMMWWMMWX0kddO0kxdoOXNWWXkcl:'cxxok0OkodxodOOxoc,.',lOd,.,:lcc:;cll;';::c::c:;,:clllxkxxkddxkxxxdoo:'
.....,:;,,'...'',:lddONWNNX0OOdldl::clc;,,;,,;:lo:;cc::ccc:;'';;:c::coxdc,';ccllclddc:codOOl,,:ol:clcc:clllc;:::loccc::cc:oxc:codddl;,:ll:okOOKNNKxlckKx:;;,,,'';c:,'',';::looooo:;,,,cdo;,:dOXWWNNKOXMWWWWWMMWWMWKdox0K000OKXXWXo::;:xkoxKKOdxxdddkOdl:..,cOO:,:::ldl:cdo:,:lollodolodoooloo:coooxo:ooclxdl
.....',,......''',,lxk0K0Okoloc;;c:;:;,,,;,,;ccloodddoll:::;''';clllcccc;'':doxkxocc:cloolc:;cdxoclc;;:c:::;,,:lolllllcccldkl';llcc;':l:cllcldddoodddkOd;;,,,,',cdo;'.'';;:looooc:;,,,cdl;,;o0XWWXXKOKNKO0XNXKWWWWWN0kk0K0Oddxk00o:l;,odok00kdkkoodkkolc'.';dOo;::;:lc;;:;,;:looloolcc:,;;:lc:cclooc:lddlloo
'';;:oxdc,...',''',cdxxdool::c:;:c;'',,,,;;:looldxxkxdl:;;:c;;;;cc;;:c,;;',:odoolclddddddoc::ccc::;..,,;,'''',:llllclloddkdoc,,ll,,,,coooc:;;;:cclcoOOOd:;,,''';oxd:'.'';;:looocc:;;;;cdl;,,oKXNNKXKk0KkooxOO0XKXWMXkOxlddxxxkxxOo:o:'cdxxxxdloocccoxooxc'',:lolcdl;:::llcll;;;;;cccc;;;::cl::ll::lc:cxxoxxd
'',:clolll,';,'';';lloddxxolccclc,'''',,;;:cllcclc:ccc;;''','',,,,'',;'','.,oxolc;;clodollxxl:,';c::;',,,;,,,,'''';c:;:cldddc''::;',;;:ll:;;;,,:;,:oxkko;,,,''.;dkd:'''';:colllccc;;;;odc;,;o0KNNXX0xkKkdxdx000O0XNXkdl::llllddodl:l:';odccclddOkoccddldl,.',:ol:ooccddokxxdc:;,:lddoccdkdl:;clcccokxlcccclc
..'cl:clll'....,,':ldxk0K0xolcloc'.'''',;;:cclxxlcc;,'';c:;',cl:,;,',,'';,.,cc,,,;:looddl;:ool:;cool:,,;;,;:;'.'';::llcloollc,':olcc:::llcc::;,:llldOkko;,,'''';dkd:,''',:llcllc::;;;:oo:,,;lk0XXXX0dloddOOkXNXNWWXOool:oOkdx00KKKd;,',ldxkdkK0Oklccldl:;...,;ldllddollcddlc;:::cokOdcoddd:,,;,;c;clccclolc;
.',:c:coo:'.''';,,:oxkOKKOoc:clc,''''',,::clcoxo::c;:::llc::ll:;;,';:;'.,,'';;;;,,;cdddko;,::oo:cod:',:,',,;;'.,cl:col::oxxddl:lOOxxdoclllccc::odxxxdooc;,,'',';oxo;,'',;:cccllc:;;;;:oo;;,,cxO000Oxoc::cxxkXNK0KKOdlxkllkOXWWWWWW0lc;'lOKX0dxdoxdodlc:,,;'.';cdoclxkxdcclc:cc:cddlcc:::cdl:;'.';::;,;llodl:
,...,coc;',:::::,,;loddkko;',;;,'..,,,,;cldd:;l:,''',',,,,:lo:,;,',;;;,',''',;;;,,;:oocol:;;::c;;col:lc:''';:;,:ldoodo:,:loddl:oxdlooc::::;,,,;:ccclocc:;,,'',',lxl,,'',;:c::ccc:;;;;cxo;;;,;loooooodl:cldkxkOxlldkodOkdcoKNWWNWWWNkc;,lO0OOkOxxO00Oo,,l0Kc.',;ll:cx00Ol:c,,coooo:,;;;;;clllc:,',c:,',;::cc:
;,,,..''..',;::;,',:::cc:,..','''',,;:cldxdccc:;;:::,,;;:;;::;,,;;;'.,'.';:,''.',;:cddddl;,,,;ll::;;cc;''';:lcccccdkxlcc:cc:cl:cllooddodollc::cldkdlddlc;,,,',',lxc,',',;:::ccccc;,;;cdc,;;;;cclodkOkdlcdkdoxdddddlclxkkxccOKKKNWWWNkc,;dKN0kOKOxdl;,looxOd,.',;;,';oxo::;';oool;'',,,;:lc::lddllc:;'''',;:l
l;,:;;;,.....',,'',;,;::;...'',,,,;clooxxoc:;;,;::c:;:ccc::ll:,;:,,''','','',,'.;::loool:;:cccc;'..';;''';;:c:,;;;:odxxo:;;;:,,'';clddoolc::oo:cx0Oooxko;,,,,,,'cd:'',,,;;:;:ccllc;;;:c;;;;:llldOKXK0xlooddkOOkxddl::lxxkkocdO0KXXK0Od;:xXXOkOkdl;',colc:od;.',;,.':o:;:cc;;lllo:;;,'';c:,;:llldoc;,....',:c
:..;::;'......','',;;:c:'..'',,,;:clodxo;,;,',',;',;,:do:colloc,,,'''.,;;,..,,'',;ldoc;,'';,,;;'..','',;;;'';,',;;;:;cddl;..',,;,,;lolc:,.':cclodxkdlloc;,,,,,,':o;',,,,,;;;::cloo:;;::;;;:ododkKNNXKk:,;:lddoolcol::lox0K0xc:lxkOkxkkc,lOOdodo:,;cloookxcc:'.',;;cddc:c:;,,;clc::cc,';cl:;,,,,;;,;;'.....';
,,'.....'....','',,:lcc;..'',;;;:clodo:'....''.......,;;,,;:lo;..'.''',,,,,ccclc;:dx:',,,''....','''',;::;,.','';;::,,:loc;;coodl;;c:::::,,,;lOOolxkoccc:;;;,,,';l;',,,,,,,,;cllol;,;c:;;;cdodkOKNNXKk:';:cc;:c:,:ddoddk00kkxlcclxkxxdc':xdc;,,;coodkdldddl;'.',,cdo::cc,'',,:;;:ldl:;;llcoc,;cl;,,,;;'.....
.''.....''.',,;'.,:loc:,.',,:c:loddoc;''.....'...'..''',;;,,,,...''..''...,cc:;,;loc;;,';:;',;,;c:;'',;;'....:c;,,,coclddc;:lxdlodxxlloc;;;clooc,:ddc::::;;;,,,';c,',,,,,,,,;clllc;,;::;;;ldddkOKNNXKx;',;,;cllloxkkxxxk0K0kxkOd:;:lxko,,:;,;:clloc:okOOkoll;..';:lc:ol;''';;'...;lollll:,::;:dd;,;;,;;.''..
...........;;;,'.,cl::;''::coloxxxo;.......''''.....'........'',;;,..''....;od:,;:;,''',;c;'',;:ldl,'cdl,...',,''';llc;;colc;,;:clcl:colcldoldo:',:,.,c::::;,,,,:c,',,,,;;,,;clooc;;;::;,:odddxO0XNNNOc'',,,:olccldxdkOOOkdccool:,.';cc,','':cccoolcokkxxc:lc,.';;cl:co:,::,,,'.':clc:lcc;',;,,;;,,,'.......
....''....';;,,,,:lc:c:;:loxxxk0Oo,..',;'...'............''....';:,',;;'..,;cc;''',;',;,,;,'.,,,;c:'.;:;;'.':l:;;,;c:;,,:cldo;,:llcoooooocll:cdl;;:'.,c::::;,,,:l:',,,,,;;;;;:ldxo:,;::;;codddxx0NWNN0o::;;'.,;:::;clllllolc::c:;,,;;''..'cdo;;:cc:;;loc:cloc,.',;:l:;:;',;,''.,:lll;',,,'.....',,;::,......
',,;,'...';::;;;;lolloccoxO0kkK0d;....,;'.',,'. .......''....',''...';:;,:olcll:,..,';c;.....,,.........'',:ccc:c:;clc'.';coc,',clol:;,,:cll;,::;;;..,:::;;:;,;cl:,,,,',;;;;;:ldxd:;:c:;;ldoodkk0XNNXKl';;'..';;;:::;;:c:::c:;,,''',,,'..,lkl,,,;::;;:cc;;::c:'.',;ol'..',''...';:;;;;,..'''.''',;;:;'......
,,,,'....',:lc:;:llcllclxOKKO0Xk;.''.','''..,;'.. .....',''''',,'.....'',:c:;ldc'...'..'................'';c;;:llc;,,'....','',;clc;,'''.':;'....''..;c:;;;;;,;co:,,,,',;;;;;:cdkdc;:::;:oxddxkO0KXNXXo,;;,'..';::c:;;:oxdl;,'''',;:::;..':lc,,;;cc,co:;::c:;:,..';lxl'''..,;,;;,;:;;;,'..,,,,;:c:,'...',,::
,,,......',;::;:cc:;:;:ox0KOOKO;.......'''......  ....,;,'..........''.',;;oddo:,'....''.............''''...',;cc;'.''........,,cl:,,,'.''.....'...'.;lc:;;;;,;ll:,,,,,,;;;;;;:dxdc::;::cdxxddxkOKXNNNx;;cc,..,:c::;;;:cll:'''';;cccol:'..;ld;';,;:;::;,:odo;,'..',:dd'..'''',,,.;c:'......';:;;,,:;,''..,::
.........',;'',cc;',;,:lxOkxO0c.''....';'...........'cdolcc:,'','.''...';;;clldl;''',;:lc;'.... ..''.........'..';,',......,,...';;'.......''.','....:lc:;;,;,:c;',,,',,,;::;,;lxocc:,;:oxxxolodk0KXXNk;;::,',::;:;;cc;'.''',,,,,;,;:c;'..,cdc,;;:cc;,;;:odl;,....';ld;.','....'''',::;;;,..';,...',;:l:,,;:
'.......'',;,';l:'',;;:oxkdxKx;,:;..,;;,...........';:cc;;cl:,'''.''...,:llclol;'...',,:dd:......''''...............''....,'.....''............''...'clc:;,,,,:l:',,,,,,,:::;,,cdo::;,,cdxkxolodxO0KXNk,;c;;;;,;;c:;:c:;c;''''..',,',,''..';od;,cc;;:ll:col:;,....';:oc.',.........';clc::,..',...';;,''.,;;
..  ....''',;;:c;.,;:;cdOkk00l,::,;:',,.............,'.';;,,:c:;:;..'.,ldkkxxolc:c;..',:lol;;:,'',,',:;,''''.......',''',::,............'...........,ccc:;,',';l:',;,,,,;:c:;,,:odc;,,,cdxxxooodxOKKKKOc:l:;::c::ccccc;,:c;'....',,',,,'...;ll:,,,,,;ccll:',,',,'..,;lo;'''........'',;;;:l:.''...,,,;:;,;cc
........',;;;;:c,';c:cok000Kx;...'','........................',,;;,,'.',coldkoccoko'.';ccc,,ccccccc::lxxoc:,......''....','''''.''...  ............':c:::;,,,';ol,,;,,,,;:cc:;,,cdl::;,cddxkdooodkOOO0Oc,:lccc:cllcl:;:,,;;'...',',;;,;:'..,:xd;'',,,:clll;,',:c:..,;cdl.','.......'',:l::lc::;'..';::;:clc:
........,:;;:cc:'':c:ldk0KK0dc:......... ...;:'.. ......... ..''';;;.',,,cl;;,;:okl'';;;,'''',:;;c;;;'cko'''..................,. ..............'..',:ccc::;,,,,lo:,;,,',:::ccc::lolcc:;lxdxkdloodkOOOkkl;,'.',,;;,:c:::,'''....',;::;:od:..,cxxc;,,;;;::;;''.','...',;dx;..........''';c;:oodoloc;:cddldkxxd
.......',;;;cclc;,:::coxO0Xkc'''..........'.,,'........... ........'..''.',';cloxxc;;;;.';:'..',:;,cl,';:..'.........   ........ .....,,:cl;',,,,,.':cc::::;,,';lc,,,,,;:c::cllclool::;codxxoloodkO0KOxo;'''';c,..',cl;........,;:cc;:lc,...;odc:c:cc:;:::,'........',lOl'''........;,...,lcclldlccodolcoodd
.......',;;:;;:l:;;;;:ldk0Xx;'.....      ..,c:,.....';'......''',;;;,'''.';;;:lldkddo;..',;;'...,'.....,;'.,'........     ....... .. .,;:,',;;;,.,,':::::;;,,,;cdl,',,,;:cccccllllll::;;coxxdooodxk0X0xxxl'',;cc:cc;;::clc;...','''.,,,;,...;oxdlcccl:',,,,'..'',,..',:xc..,,'......,'.....,:ldo:looodl:;,,;
........,;;;,'';;',,;:clx0Kd....       ....,;;::,...,;;;,'...,::clll::l;'':ol:;;;ckd:,.'',,,';,','..''';,.... .........       .....,,......,;',c::c:::::;,,,,,:ldo;',,:oollcccllooooc:;;:cdxxxooodxk0kddkd;',,;clllcclclolc;:c::;''',,,::;:,;;;co:,,:;,;,;c::;;;;;'.',;lc......',,'',,''''.,;::;,,;;cl;,'''.
........,,;;;''''',:lddod00o...    .....''.,;;''.. ...';;cc,'';cc:;;;:c;',:lol;,,,:c:;'.',:lcclcll::;;ll,..    .....',.  ..   ...',,;,..,;;......:l:::::;;:c;,,;oo:'',ckkool:cclooddo:;;:codxkdoodddddddooooo:;,,:cllc:odocclooll:,,,'',::,,,',cc;,;;;cllcl:::;::,'..',co;....  ...''........'..';;;c:'',c:,
 .......',;;;,''',:lxOkkkOOo,.... .........,:;,...  ...,,';:;,,:::lcc;;cc::;;c:ldlcc:;;;,,:lc;;,;;;;'',,'......''...,;'..'..    ..'..'..';;...',',,;:;;;;;:lc,,,:l:.';coodkd::cclodddl:;:codkOxdooddodxxoldkkxoc,';cddcoo::cc::;,';;;,,;ccc;';lo;;:;colldoododdoc'...',;lc...................'..','.',,;::;,
........,,;;;,,,,;:lxO00OOxc,..,,'''',:l:'.':;.......',,;;,,,,';:;;::codk0d:clclxkxo::dddoc:;'...';;,,,'',;,..,;:,..,,,''..      .......    ..,'.;;;:::;;,;lc,,,:o:',;:;:dOd::ccllodol:;:coxxxddddddddxxo:;:coo:',;cll:;;;ldo;'''.',:;;clc::;,:lc:ccoxdolloxxkxxo;,...,;cl;...................,,,';,''.;:'.'
.''....,,;;;;,,,,;:okO0KOkdc;,;:::cllodxd:...........'..''''.'..,,'.':xkoxxllxxlccldkkd::ollc:,'',;,''','',,,'..,,,,','',...   .  ...'.     ..;:,;::c:;,,,:oc,,,:l:',:::oxkd::clllodoc:::cdkdcoxxddddxxxo;',:clc,'';:c::c:clc;;:cllccccccc,,::::clclodocclloolclcll;..',:ll'.............  ...'...,,'..';,..
'''',,,,:c;,;;,,',coxO0KOxo;,:,.',;::cddc;,''......,cll:'........'..,;oxl:lloO0Oxollccl;,;;,,,',,'',,',,'.'','...,:::;'',,''.. . ....,'.......';,',:c;,'',:l:;,,;::''cccdxxdcc:cllollc::::okxclOkdxdodkxo:'';;:c:;;:cc:;;',::;clloddlcldl:;,,,cdxddoool:;cllcccc::lc,..,;ld;.   .............'..............
'...''',;::;;;;,',:oxk00kxo,.....';;;,;;,',;:;,''',,;:lc:;'.    .....,;,,;:l::okOxdd:.';,;,''...','...,::,,:,...','';,,,',,,,'.....................;c;,''',;;,;;;;c,'c::dkxdolc:coolcccccclkxclxddxxdxkxdc..';c:;:c:clll:,,::::;,,:llccdxdlclcodollclcc:;:llcloclocc;..';co:. .........',...,'..............
'...,',;;,;;;,,,',:odxOOkxl,',,,,;clc;,,;:ll::;'''..,::;,...     ...',,'''';::cxkocl:'..'',','....''',;cdl,;;;:,..',,,''';;,'.''.....      ......',;:;,'',,,,,,;'';,,c::dkkxoclc:cccccc::cokxcckkxxxdxOkdl'.';odll:',;:;;:;,;;;;::cclc:looollcclolc:;:;,;;;;:llclol:;',;;;cc,...........'...'...............
''.',,;cc:,,;,;;,,:oddkkkkdc:;;cc;:ll:;coldolc:;;::'.,;::;,,.   ....',,::'.,:;cdxl,;;'...'',;,'...';:c:::;,ldoodc,,,,;'.''.,;'',,'...      ......,;::;;,',,,'';,'.'',;;:dOkkd:cc::c::c::::lxxcck0kxxxkOOxl;,';loc,'...'',;:c::llc;;;cc:::odddoccc:lc;'';;;;::cccclc;,',:;;;c:',,...   ..',........   ....',,
''..''';:cc;,;;,',cooddxkkxkkxoxo:;,;c;::;,''',:,:c;''',:lo:.......',',,,';;,,,;:loo:'',,',cl:;'..';;;:;,,colcldo;'..'.....'',,;ll;,,.. ..........';;:c;;:,,'',,,...,;;lk0Okxollllcccc:colcolcck0OxxdxOOdoc,.'::........,;:lcloc;;,,,;:,':odollc:;;;'',;;;;cc:;,,'''''''';:c:,,,'..    .';,''.....     ..':l
,,,,,,;,,cl:,,,'';clllodxxdodo::,...',:c;'..,,:oc;:c;'';:cl:,';;;:cool:;,,,,,,,,;:lc;;:lol:;cdxdl;'.',,,,;:c;;ldl;cl:'..........,;,',,.......... ..;;:l::l:,,',,'...,;:dOOkxkxdlodlcc:cddollcllx0kxxkkOOdddc;.....',,'.';,,;;::,.''''...,,';c:,,;;,'',,,,,,;;;,'''...'..',,;:;;,,,,''....;;;;;:'..     ...,c
'''.',;,,,''.',,,;clllloddolo:'.''....,;;,,;',cddl:,;:;,;:,;olc::ldxxddl,',,'',;c:'''';col::olcldxo,.''',::clc:::::odc'... ..'''...','''...''.....';,:ollo:',;;;,'.';clxdxkxkkdodxdol:okxddddoldkddxOOkOxdxoc,.'.',,'..',,'',,'....',,,,:c:;cc:;;,''','....,;'''''......''.';;,,;,;,,,'';c;;;;:,..   .......
'.',,:;',;,''.',,;clclllodlloc....,;;,'''',;,';clcc:,,;;lo:;colllccc::loc:lo;.':c::c;;;;cl::l:,,;:c:''..';;collc'':olc,....',;:;,';;'..',;:::;'...,,,:ooooo;,::;,'.':cclldOkkxolxxool:cdxxkkxlclxkxkO0kkxoddol,......;l:';ll:;;;,.':c:::::c::loc::'''.''''..'.............'',,,,,;;,',;;:::;:c:,...  .',,,'.
.',,;cc;;,'''.''';cccllldko,,:,...';;'..'..';;,';:,''.',:c:,,:ldxc,;,,,;;;;;,';:;:c:;,';,:c:lo;'';ldc;;,..,;:;lc.'::::,'.,clc:cxxo;'','',:c;;,....'',cdoldo;,;:;,'..,;:llokOOdccodollclddoxxxlcdxxdk00Okkddooxo;,..,,;c:;:,..';c,..;cc::c:;:c:cc,''.......''''...'............';;;c;',,;:cllllc:;,....',,;:,
''',::::;,,;;','';ccclloxkl;,;;'..','..''..','.....','.,;:;,,:ddxl,:c;'''''''',,,cc:::;'':c:l:...;lc:,,'.'',:::;,';;,';cc;;c;;;cddl'.,,'.''. .',..''':lcloc,,::;,'..':cccdkOOdccoolccloxxdxxxc:looxxO0OOkxdc:dd:,.'cc::;;:,.','''.,:c:;:clcllccc;,.............'...........'..,:;;:,''','';:c:;;;,....','','
,'.,::cc;:ll;,'.',:::looxxooc::'.....','''............',,'.';;cl:,..,'...',''..,;;;;cc,..;::;.';,';,......';oocc:cdl,';;;,;lloo::coc,:c'..    .'..',',,,::,.';;;,'..,cllldxxxoccoolccldxxxxxxc;cldxxxOOOOxoc;c:;,,;:;;;;;::;::;,'.',:ccccccccc:::;..''......'....',..''.'....',;;',c:,,,'.',;:;cc;,,,''...'.
'',;;;::clc;.....,;;:lodxdlc;'.......;,.....'.....  ....''...',,..,..'..''..';;;;;,,;;,''......''',:,.....';;;clolccccl;:c,,:lc:cc::'...   .....'.',,'';c:'',,,,,'.,lddldkxocccllll::coxxxxddc:clodxdxkOOkdl:;;,..'''..,,,',,;:lol:;;:c:c:,,;:,,;;'............',,'..,',,..',;,',,;:::;,'',,;:;,,;;;;,''....
',;',ccc:cl:;,..',,;:lddxdc:;,'.......'................,,.. ......'..''''...'::l:'..'....      .............',:::::llc;:l:,,col:,,;'.......,,:cod:'''''';;',:;,,'..;oxdoxkdoc:clllclocoddddl:::clodxxdkOOkoollo:''..,,,::;;,';clodl,.';;:;;:::,;,,,............';,..',,,,'.',;,,,',,,;;:;,;::;,',,;;;;;;,'..
''::cdddlclloc,'',;:cldodl,'''......'......................       .:;'','....';oo:;,'..       ..,,.'.....'..;:;'...'::;cc:;,;;c:'';;.....',,,lodd:..''''''.';;,'..;ldxooxkdlc::clllO0xloxxdl:::clloddxOO0Oodxlc;;;::;',;'';'.,cc::c:,',;;,'',,.''........ .....',,,''',,'.....','...,;;;;;,;;;;;,,,,,,;;;,..
.,clclllllc:cc,',,;:cllll:''.....,,...',,,'.'..'.....','..       ..;;,;;,.,;,'.,:;':c'......';;::cc;'.......''.',,'';;,;;;::;,''..';'.';,,,;',:::;...'''',.',,'..,cdxxooxxdooocclclOKxlloddo:;:ccccodk0KKOodd:,::ccc:;:l:,;,'.':c:::;;;;;;,............ ........'',,'''''.........',,;;,,,,'''',,,''''',,,'.
',:oc:cllllcoo:,,',:cllc;'''......'......'.....,'....''''.   .. .',,,;::::ld:,';,..''...'..',;;;,,;'';'..''........',;;,'.,::'.',,,'..;:cc;'',;::'.'....''..''...:c:lddloxdocllcc:ck0Odooodd:;:c:;:cox0KKOoodo:ccclol::lc:c:;,;cc;,,::,'''.........................''............'',,;;;;;;,''''','''''....'
,,,;;;:::;,,;;'',,;:ldoc;'''.... .............'''','..'....... ....,'','':clc;',;''.....'.......''''','..,,'...,......:;,'..,'.',,,;;,...,cc..'::'..'.'.''...''.,c::ldoldxdxlllcl:cdOOkdldxdc;:cc::clokK0xoodo;:lclooccllllloo:;;''';;;,.....';,'.....''...''.......'.',''..,;;:;,'''''',;;'.''''';;,''.....
;'...'',,;;;,;:::;:coxdc;...''..................',,''''...        .'.'....;;'.'',;'.';,.......''''''.......'...,,'....,,'......;:::c;,....','.''''.','''',,'....,::coxolxxdxlccclclxO0Odcdxdl:;::;,;clxOkdloxd:,,;::;:looc:codc:c:,:o:''.......,;,.'..,,......','....';::cc:;;:llc::;'..,:;,,,',,'','......'
....''..';,,;;;cccccdkdc;...''...,...............,;,,'....   .. .....',.....;;::;,'',;,''...,;,.... . ..'...',',,;'..':ll,'..'',,:cc,,.............,::;,',,'....';:cloolddxxc;cloldO00Oo:oxdoc;;;;'';coxxdodxxl,.';:;:ol:;;c:;:::c:cc;;;,'....',;:cc::;'.,::,';::;,,'';::::c:;;;,;:c:,..','',,',,,',,''',''.
','.'....,cl:;;,,;clxOxc;'......'..................';,......,,';:;,::;''....,,'...''',,'...';,..........''..,::;:c;,;:,;;,;:;:::,','....',,::,.....,ldo:''''....,;::lllldxkxc:cll:lkOkko:lxddc;;;;'.';lxkdodxxd;''';;,::;;;:::;;:::::;:;',,;;;cclolclc;,:lll::::;,;;,,;,,,,,,;;,,,,;;::,'..''',;cc;;;,,'',;;
''......,:ll:cc,';clxkdl;..........'''.',,''','.',,;;;,,'......,::,','......;;'.  .'. ......''..  ..........''..,;:;:llll:::;:,.,,,;,.....',:l:'...;odo:''''....;;;;::cldkkdccllc;o0kolc;:dddc;;;;,...,cododdddc'..'coo:,;,;::,;:clooooolccll:::clcllc::::cc:;;;,',,,',;;,,,;,,,'''',:c:,''''''',;;;::;'..;l
.........';;:c:;;lc:oxol;... ...  .''......',,,;:c;'''.'....    ...... ...  .... ..'...........   .....;'   .....'''.,;;:,'.,;'.',.......,,',;;'...;ll:;'','...'::;;;cldkkkdcllc::o0xc;,,:ldoc,;;;;,...,:oddxddo,'''';clccccdl:coddlcccooc:::;,;::::cllc:;;;;,'',;::;:lxdc:ll:;;,,,..,;;,''''.......'''.';;,
..',,',,','';:;;:l:;lddo,... ..  ..',,,....''.'',,,.             ..    ..     ..';:;,.... ..........'',;.  ........',;'.'........'.''..'''..':,....;l:',,,,'...,cc:;:ldOOxxoclll::x0d;,,:;:oo:,,;;,;,...,cdxxddko:;;,,;ccodolccloddc;;;::;:::cccllccccc,,,,,,,,;:lloodxxdc:::;,'..''....'................'..
.,:;,'''','...'',:,,lkko'........'''',,,,,,;;'.....  .          .       .......';cc;'',''''...''''..';;,'.....''....''',,;:'.....'..'','',,',;'....,c;.';'.....;cc:;:ldOxoddccll::dkl,',c:;lo:,',;,,,'..';ldkxoooc:::;;:::ooc:;:c;;;;;::c::cloc::;::;;,'',,,,;clodloodxoc:;,,,'.............................
'..''...',,'.....'':dkkl..'::,,,,,,;,'.,,,,,,...... ..          .      .'...,,';:;,,'.;lc;,'.'''..'''',,'..'..',...'.'''',,','..',,,,'.....''''.''.';,.','....':ll:;ccdOdloo::cl:col:,,,::;clc;,,,,,',,'';:oxdlcllcllc:;::oololll:;;;;:clc::::;;''''....',,;::loodl;;:c:,,'''........................  .... 
'..''.''';:,.......cxkx:...,cc;,,,,,;;;;;;:;'........ .... ..  .... ....'''',;:lc;',,;cc:,.''.','''''''''''''',;,.',...',,,,'.'';ldl:;;,'..,:;',,'',;,'''.....;ooc;;:lk0xllc;;::;cc;,,'':c;coc;''','''',:cclolcccc:;::;;::c:;::cclc::;,:c:::;'.............''',;,;;'',,'''...........  .....   ..  .. ......
'..,;'.............:xOx:..,:ccc:;,,:;;::;;clc;''''......'......,,'..',,;;;::;;::;;;;cc;;cc;,,,,,,,;;;;;:c:,::;;,,,;ccc::c:;;,,:coxkdollllc::;;:lo:;;,'';:,''..;ldl:;cx0Oolcc::::::;,,''':c;clc:,'','..',;clllcll:::;;::,;::;;:;::;;;;;;;;:ccc:;;,......................'..............   .... ..............
'',cc::;,'........'cxOd;;:lo:;c:;,,,,;;,,;;::;,;;;;',;,.','..',:cc::c:ll:cllllcllcc:,';c::;,,;;;;;:ccccllc:cc:::ccclccodlc:;:ccclolclc:::::,';cod:,:c::lc,'',,,clc;;oOkl:ccl:;:c::;;,'',:c,,;;,,'',,'..'',:llcldl::lldl'',,,,;:::;;;;,,;:oo:,',,;,,,''.',::,'...............................................
:::dkOd;...... ...';oxc;codddlc,''''''''.',,;;;cc:;,:l:;:::;;cloddolllooccloolllllc:;;::;::::::::::cc:cc:cc::::c::cllodl::c:lllodoc:;;,;;,,,;::::,,;:::;,...';:cc;',ldlcclco:;:cc:;:;',:lc,''',,''','...'',:llcldoc:dkl;::,''::,cc;'''',;cc;''...',::;,,;::,,''...............''..........  ............... 
;:;lodd:...... .....;:,;lollccc'....';,'''..',,;,,,;::;;cllolllolcl::lc:cc:;:cccc:;;:::;;,;::::loc:cccccldolccodlcooloolc:;:lllooc:;;;,;;,;;,,.';::;,''',,'.',;lo:',ldxoclol;;:cc:;:;',cl;',,',,''',,'..',,,;cl:lxo:ldlldo::;:;;;,,,';;;;''.',,,'..,;,',,'''''......'''',''.............     ........... ...
coc;:;;;,;'.....,...'::::::c;,'......''',,'.....,;;;cc;;:::ccc:;:c:::;;;;;;,;:::;'',;;;;;,,;;;;:llllcccclc:;:cc:ccoo::cll:;,:c:lllol:;,,','';,',;'';c;;:c;'..':oo:.:k0kolodl;;:lc;,:c,,cl;.''',,,'''''...';,'.',:oxdccoolccccc;,,,,,,,;:c;'.,::,''',;'...'',;;,;;;,,'''''''............................   ..
:clc:;:c::;',,',;,..':lllddl:,,'.'''...'''''''',:c:::;,,,,,,;:;',;;,,,'',,,,,,,''.',,,,,,,'''',:loll:::;:cll:,;:cl:;:::;;:c;,:cc:cooc,,,,'':l::;'...;cc:;,''',:::;,lOOkddddl;;:cc:,co;,::,..''',,,,'.....',;,...,;lkxollllllc:,'',;:;;,;c:;,,;,,;:::::::::;;;;,;;,'''...''..................................
.'co;';;',;;;,;;,,,,,',;:coddlc:::::::;;;,,,''',,;:;,'.....'''.....'''.',,,,';:;'',cc:,,,;:'.',:ccc;;:::;;:cc:c::c:;:lc:,;c;,:c:;:::;;,'''':c;,.....,,'''''',:c:;,;ddloxddol;::c:;,co:,,,'...',,''''..'''',;,','.,:lxkoodo:;:;,,;;;,,;'';::;;;,::;::;,''''''''.............................    .............
ccdo;,cc,',,,;:;,,;;;;;clc:::::c::;;;,'.....';,,;;;;;'''''.'.......''',;:ccllcc;;:::::;;;:c;,;;;;;,,,,,,,'.'''',,,,,,,,',;;'',,,;;;,,,'..,:,.'''',,,,;;;,',:cc::;';clooddol:,;c:;,,;:;'''....',;,'.''',,.',,,,;,',,:oxxoooo:,:cc;,,,;::,,,;;::,,,,,,'..................................... ..  ......... ...
xdkxdoooccl:::,,'...''',:;;;,,''''',,'''..',;:;;;;,,'.','''''',,,,,,,,::::::;;::;,,,,,,,,,'',..,,'''''.'............'''...'''.'',,;;;:;,',;,,;,,;,..';::,,:loo;'',:cdxddxd:,;:::,,'',,...''.,'.,;,'',,'','.',,',;,,;:loxxocc::,,,'.,,,,,,;,;,,;,,,,,,',;;................................... .............''
kkkOxddxxocclc;:c:'.........'''''',,,;;:c::;;;;;,'''...''....'''''....'''''''''.'.....''''..........................'......',;,''''.'''..:oc::::;;,.',''';ldxo'.;ldkkkxxko;,:::;;,',,,..,c:....''''..,'',,'',;:;;;,,,,cdkkd::l:;:;,;,''''';;;;:,',,,;;,,,'.....................................''''',,;;;;;;
xddlcclool::clooool:::;;,,;:ccc:;:c;',,',,,''..........''...............................................,,,..............,;;;;,'''',,....;ll,,:l;',.'..;:lxkxc.,coxkxxddxl:::;;;,'',,,'',;'.............',:;;;::;;:;,.,codxlllolc:col,''..',;cl:';:;,;cccc:;,,......................';;;,'''.',,'',;:;,'....
lc;,;::colc::clddoodddolc::::;;;,,,'.'............................................................''..':::,....,;,''...,,;;,,,;;;;,,'....;c,..,:;''..',:ldxxl'.,coxxxxdkkl:::;;..'',;,'',,'... .......''',,;,';:;,;;'.';coolodxddxololll;,,,,;;;,,;;,,;::::,,;,,'''''...............,:::;;,,,,'.',;:;;'.....
.......''......''..',,;,'''.............................................',,,,,''',,'',;;;;:::clc:::;,,:::c:,,;;:looc::;,,,,,;::::;,'';;,.','..,:;''',:cldxxc..':lxkkxxkOxc,,:::,'''.'.................,,,,'....''''.',;,,,:oloddxxoddokx:::::;;cc;clc;,'',;;;,,',,,,,,,'.'''''''......  ....;c:;;'.';;''....
........................................''',,,''........''''',,,,'......',,',c:,,:cc;,;c::cc:oxdodddccddool:,;:c:::;;;;,,,'''''''.''',,',;:c:;,,:cc:;codxo:..':oxOOkxxkxc:'.,:;..'..''',,,'......''...',,'.',......';ccc;,';cllodoclollodl:;:::cllll::c;''',::;;:;;;;;;,''''''''''..........';,''',,,'......
....................''',,,,,,,,,,,,;;;,,,,,,,,,,,,,,;;,,,,,,,;::::;:::;,',;;;;,;::cllccol:clclc:clddlodoooc::::;,''',,'.''......',,;:;,,;,,:llc:;,,;coooc'..,:odkkkxkOko:,'..,,..',.',,,;,......','...'''...,'......,::ccc;,;cllol:,,;:;;:;;::clc:ccclol,''',:,',,;;,;;,'''''..''........,..'''.............
''.',;,,,,,',,''....''''',,,,',;,,,,,'''''.''..,;;c::c:;:cllllloolldlloooolloolllllloddxxddlclc::ll:ccc:;;;;;;;,,''..........''..,;;,,;:c;'..',ll:;clcc:,'',:cokkxdodxdl:,'''....',;;:;'...',,,'........................;cllc::ccccc;,;:,,::::cddoccoxdo:::ccc;,,;c:,'''''',,,'''''',,.,;'';;,'','','',''...
,;;;:c::::;;cl:;;::;;,;,,;;::::c:;:cc::;;:cllccloodddxddxxxddxxxkxxkdoooddddddddooodxxxkkkxddoc:;,,,,,''''''','''......',....''',,,''';c:,....'looool:;,..'clodOkkOdl::::'.''....',;,',:;'',;;,........'...............'''cool:;;;::::cc;',;;:codoloolldxdololcllodolc:;;;;;;:::::::cc:ooclc:::;:::;;;:llcc:
;:codoccc;',:clc::cc:;,,,,;;,,,,',;:::::::cccccc::::cclll::cccllccccccllodoooddoloodddxddoc;,,''..'..''.......'''.'...,::;'';;,'',''',,::,...;looddl:;,'..;ldk00OOOkd:',,.....'',,.,;..,;:;'',''',,;,............ ....,,,',ldoc;,,;;::;:;'',;;;:olclclodxdoodxxlcllc:::::;;:cc:::;;;::colllloooooooodxdxkkkx
        """

        try:
            if int(choice) <= len(biomes_dict_list) + 1:
                choice == int(choice)
            else:
                raise ValueError
        except ValueError:
            return plant_biomes(arboretum, plant, menu, plant_menu, "* Please input one of the numbers listed above *")
        
        else:
            if int(choice) == len(biomes_dict.items())+1:
                plant_menu(arboretum, menu)
            elif int(choice) == 0:
                menu()
            else:
                biome_class = biomes_dict_list[int(choice)-1][1][1]
                if len(biome_class.inhabitants["Plants"]) < biome_class.plant_capacity:
                    biome_class.inhabitants["Plants"].append(plant)
                    menu(f"~+ Successfully added {plant.species} to {biome_class.name.capitalize()}! +~ \n {message}")
                else:
                    plant_biomes(arboretum, plant, menu, plant_menu, "* That biome is at carrying capacity, please try again! *")
